### ISSUE TITLE
Problem connecting to keycloak

### ISSUE THREAD

**Issue by noromamai** [pulsejet/nextcloud-oidc-login#10]
I installed a keycloak server and followed the instructions on how to set it up. almost got it working, tried a lof of different settings, but can't get passed this problem. When i click the button i am redirected to the keycloak server auth page, i enter credentials, get redirected back to nextcloud, but then i get a message "Could not verify signature".

in chrome developer console i can see an error stating: 
"This application requires JavaScript for correct operation. Please enable JavaScript and reload the page."

But javascript is enabled in the browser

**Comment by pulsejet** [comment]
Hello!
As such, it shouldn't require JS to login as far as this plugin is concerned, so this looks like a problem with your nextcloud or keycloak setup. As per the OIDC spec, nextcloud will verify the signatures of the keycloak server with the `.well-known` attributes, so that is probably what is failing. Have you tried setting up another client with your OIDC provider?

**Comment by xcffl** [comment]
My keycloak instance works well with WordPress + [OpenID Connect Generic Client](https://wordpress.org/plugins/daggerhart-openid-connect-generic/).
I notice that if we don't specify `ID Token Signature Algorithm` in Keycloak, NextCloud will complain `No support for signature type: ES256` (which appears to be that NextCloud may failed to negotiate the signing algorithm).
If we specify the algorithm to `HS256`, it will say `Unable to verify signature`.

**Comment by xcffl** [comment]
OK so by default `/protocol/openid-connect/certs` only have keys of ES256, PS384, RS256. As NextCloud doesn't support the former, use the later.

**Comment by pulsejet** [comment]
This is a limitation of our OIDC library. #30 will add this to the readme.
