### ISSUE TITLE
First login fails for existing user

### ISSUE THREAD

**Issue by m7913d** [pulsejet/nextcloud-oidc-login#104]
If a user is already created, but has never logged in before, the login process fails with exception `OCP\Files\NotFoundException`.

This issue is related to: https://github.com/pulsejet/nextcloud-oidc-login/issues/96. This issue was fixed by not providing the token to `completeLogin`, in case the user was created in the current request.

It is unclear to me why this token was introduced recently in commit https://github.com/pulsejet/nextcloud-oidc-login/commit/3a50a43611d859daed44b065db86b16225052404. A possible fix would be to never provide the token.

A better workaround may be the one apllied by social login: https://github.com/zorn-v/nextcloud-social-login/commit/d00c38e51eb4973eac179ad8bbe13ad5f4821326

    //Workaround to create user files folder. Remove it later.
    \OC::$server->query(\OCP\Files\IRootFolder::class)->getUserFolder($user->getUID());

### Stacktrace:
```
[index] Error: OCP\Files\NotFoundException:  at <<closure>>

0. /var/www/html/apps/files/lib/Controller/ViewController.php line 148
   OC_Helper::getStorageInfo("/", false)
1. /var/www/html/apps/files/lib/Controller/ViewController.php line 197
   OCA\Files\Controller\ViewController->getStorageInfo()
2. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 218
   OCA\Files\Controller\ViewController->index("", "", null, false)
3. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 127
   OC\AppFramework\Http\Dispatcher->executeController(OCA\Files\Controller\ViewController {}, "index")
4. /var/www/html/lib/private/AppFramework/App.php line 157
   OC\AppFramework\Http\Dispatcher->dispatch(OCA\Files\Controller\ViewController {}, "index")
5. /var/www/html/lib/private/Route/Router.php line 302
   OC\AppFramework\App::main("OCA\\Files\\Controller\\ViewController", "index", OC\AppFramework\ ... {}, {_route: "files.view.index"})
6. /var/www/html/lib/base.php line 993
   OC\Route\Router->match("/apps/files/")
7. /var/www/html/index.php line 37
   OC::handleRequest()
```

### Versions
OpenID Connect Login: 2.0.3
Nextcloud 21.0.2

**Comment by pulsejet** [comment]
> It is unclear to me why this token was introduced recently in commit [3a50a43](https://github.com/pulsejet/nextcloud-oidc-login/commit/3a50a43611d859daed44b065db86b16225052404). A possible fix would be to never provide the token.

For the record: https://github.com/pulsejet/nextcloud-oidc-login/issues/94
