### ISSUE TITLE
Login attempt fails silently, drops back to username/password signin page

### ISSUE THREAD

**Issue by starrynightspy** [pulsejet/nextcloud-oidc-login#106]
I had this plugin working when my instance was LDAP backed, but I am attempting to migrate away from LDAP. 

Removing LDAP seems to have broken it, causing the issue mentioned in the title. So I've started with a clean Nextcloud installation that hasn't touched LDAP. 

As the title says, attempting to login will bring up my Keycloak login page, and that seems to work, but once it redirects back to Nextcloud, Nextcloud drops me off at the signin page without logging me in. 

Let me know how I can help. I can't find anything in the logs.

**Comment by starrynightspy** [comment]
Nevermind, I'm an idiot. Account creation from OIDC was disabled. No wonder, huh? Closing now

**Comment by dcardellino** [comment]
@starrynightspy i have the same issue, what is your config right now?

**Comment by Sirius-KiH** [comment]
I had the same problem. For anyone else stumbling upon this in the future: you need to set ` 'oidc_login_disable_registration' => false,`

**Comment by zloveless** [comment]
Anything else to try? I have this setting off as well and still getting a silent failure. I can't find any logs to indicate what any sort of error might be...
