### ISSUE TITLE
can't get groups to work

### ISSUE THREAD

**Issue by verymilan** [pulsejet/nextcloud-oidc-login#107]
Hi there, sorry for using the issuetracker for this but i did not know where else to ask.

I have created the ownCloudGroups type as advised in the readme and added 

````
'oidc_login_attributes' => array(
        ...
        'groups' => 'ownCloudGroups',
        ...
),
````
to my config as described. now i can't get it to pass the value from Keycloak to Nextcloud... i have tried multiple variations of values in the hope that it might need a specific formatting (adding quotes and stuff), right now it's just a simple value:
![fg32w](https://user-images.githubusercontent.com/10698140/121339825-2c56fe80-c91f-11eb-8e50-a01ffa242f78.PNG)

`'oidc_create_groups' => true` is set. 

just in case i have moved to the git version, but it seems not to differ. 
Setting a `default group` option works, `ownCloudQuota` works as well, so does `ownCloudAdmin`. Just the groups don't work. :(

Please help me 😇

**Comment by pulsejet** [comment]
Are you sure the groups are passed to the plugin correctly? Maybe try debugging similar to #109

**Comment by hschletz** [comment]
How are your group memberships defined within Keycloak? Your screenshot looks like you have defined them as a regular attribute, which is not the correct way.

See also #112 for improved documentation.

**Comment by verymilan** [comment]
Thank you very much for clarifying (and sorry that i didn't respond earlier)!
With step 5 and 6 from your PR, it is finally working for me 🎉
