### ISSUE TITLE
Debug Openid attributes

### ISSUE THREAD

**Issue by tanguy-opendsi** [pulsejet/nextcloud-oidc-login#109]
Hi
I got somes troubles with OIDC app i think my provider did not send corrects attributes
How can't i verify what attributes are send to my Nextcloud 

Best Regards

**Comment by pulsejet** [comment]
Just add a print statement
```php
echo "<pre>"; var_dump($profile); echo "</pre>"; exit;
```
at the start of
https://github.com/pulsejet/nextcloud-oidc-login/blob/51a3ef9dec1d174ce682e863aa6386b36059790c/lib/Controller/LoginController.php#L120
