### ISSUE TITLE
Login with azure 

### ISSUE THREAD

**Issue by SergioRaneli** [pulsejet/nextcloud-oidc-login#11]
Hi,
I can succesfully login but on user creation a wrong (very low) quota is set.
I tried to change and remove quota attribute with no luck.
-----------------------------------------------------------------------------------
UPDATE: it was my fault, you can ignore the issue

**Comment by pulsejet** [comment]
Hi!

Did you set the default quota value?

**Comment by SergioRaneli** [comment]
I update my issue, it was just a typo in the config.php. Sorry and thanks for your reply!

**Comment by KiYiul** [comment]
@SergioRaneli, have you some information about login with Azure?
I'm looking for **_redirection uri_** to login with Azure but I can't.

Here is my config.php
```
// OIDC Login plugin
  'allow_user_to_change_display_name' => false,
  'lost_password_link' => 'disabled',
  //'oidc_login_provider_url' => 'https://login.microsoftonline.com/{tenent_ID}/v2.0/.well-known/openid-configuration',
  'oidc_login_provider_url' => 'https://login.microsoftonline.com/{tenent_ID}/v2.0',
  'oidc_login_client_id' => '{client_ID}',
  'oidc_login_client_secret' => 'secret_ID',
  'oidc_login_auto_redirect' => false,
  'oidc_login_logout_url' => 'https://nextcloud.company.com',
  'oidc_login_button_text' => 'Log in with Microsoft by OIDC login',
  'oidc_login_attributes' =>
  array (
    'id' => 'name',
    'mail' => 'email',
  ),
  'oidc_login_scope' => 'openid profile',
  'oidc_login_disable_registration' => true,
  'oidc_login_redir_fallback' => false,
```

**Comment by KiYiul** [comment]
@pulsejet, I can setup URI information on Azure, like below this.
https://github.com/pulsejet/nextcloud-oidc-login/issues/114
