### ISSUE TITLE
Hide Default Login

### ISSUE THREAD

**Issue by tammer123** [pulsejet/nextcloud-oidc-login#110]
Hello,

Will there be a option to hide the default login form, but still accessible through a link or a button, like the Social Login has right now?

**Comment by djessich** [comment]
Use `https://<domain>/login?noredir=1` to show direct login in case oidc plugin is enabled.

**Comment by l00v3** [comment]
> Use `https://<domain>/login?noredir=1` to show direct login in case oidc plugin is enabled.

Is it possible to disable this? So direct login is not available and only OIDC login is possible? I cannot find such configuration parameter.
Thank you!

**Comment by robrecord** [comment]
> EDIT: Found this: 'hide_login_form' => true, and it seems to work.

Great, thank you.

Now it would be nice to redirect to the login page immediately without requiring the user to click "Login with OpenID"

**Comment by l00v3** [comment]
> > EDIT: Found this: 'hide_login_form' => true, and it seems to work.
> 
> Great, thank you.
> 
> Now it would be nice to redirect to the login page immediately without requiring the user to click "Login with OpenID"

This parameter will do this:
```
// Automatically redirect the login page to the provider
'oidc_login_auto_redirect' => true,
```

**Comment by sirkrypt0** [comment]
Seems to be solved, so I'll close this. @tammer123 if you are not satisfied with the answers here, feel free to reopen this issue :)

**Comment by ksarink** [comment]
I wanted to mention that when you have `'oidc_login_auto_redirect' => true` and `'oidc_login_auto_redirect' => true` it is still possible to access the regular login form using `https://<domain>/login?direct=1&noredir=1`

Is there a solution to really disable the regular login form and not just hide it?
