### ISSUE TITLE
Logout with OIDC provider not possible

### ISSUE THREAD

**Issue by alesandrino** [pulsejet/nextcloud-oidc-login#113]
We are using your OIDC login plugin to authenticate with our OIDC provider, but found that it does not support to logout the user with the OIDC provider.
I have added this feature in my own repository and it works in our DEV/STAGING environment. I would be willing to do a pull request if you believe that the feature is useful and if you like my sort of naive approach.
I am not an experienced PHP developer so a close review would be definitely recommended.

**Comment by Ornias1993** [comment]
Normal procedure is to file a pullrequest to request it to be reviewed, not ask for a review in an issue ;-)
