### ISSUE TITLE
AADSTS50011 - OAuthv2 redirect URI log issue in Azure AD

### ISSUE THREAD

**Issue by KiYiul** [pulsejet/nextcloud-oidc-login#114]
Hello, I tried to login with Azure AD OAuth v2 method using app registration.

I have been create Redirect URIs on AAD as below,
https://nextcloud.companyname.com/index.php/apps/oidc_login/oidc/callback
https://nextcloud.companyname.com/index.php/login
https://nextcloud.companyname.com/

and I wroted config.php as below,
'oidc_login_provider_url' => 'https://login.microsoftonline.com/{tenent_id}/v2.0',
'oidc_login_client_id' => '...',
'oidc_login_client_secret' => '...',
'oidc_login_auto_redirect' => false,
'oidc_login_logout_url' => 'https://nextcloud.companyname.com',
'oidc_login_scope' => 'openid profile',
...

However, when I try to login with Azure AD id, the below error was pop up.

AADSTS50011: The reply URL specified in the request does not match the reply URLs configured for the application:{tenent id}

How can I solve this issue?

**Comment by jasonmc1993** [comment]
Hey! I was having a very similar issue and noticed that the URI that was being passed was the following: https://login.example.com/apps/oidc_login/oidc

Try setting your Azure AD Redirect URI to something like that and see if that does the trick.

Jason

**Comment by KiYiul** [comment]
@jasonmc1993, Thank you the most infomation of URI.

Acctually, our right URI is,
```
https://nextcloud.ourcompany.com/index.php/apps/oidc_login/oidc
```

And when I wrote in config.php as below, I can not login due to...
1. id attribute included "(" and ")" character which is not allowed in NextCloud.
2. oidc_login_disable_registration was "false" so auto creation account is disable error pop up.

so, I change configuration as below,

```
'name' => 'name',
'mail' => 'email',
...
'oidc_login_disable_registration' => false,
...
```

I can login as I expected. Very thank you much.
