### ISSUE TITLE
Login not working anymore after release 2.1.0 

### ISSUE THREAD

**Issue by antoniogfs** [pulsejet/nextcloud-oidc-login#120]
Hi, first of all thank you for this app it's indeed very helpful.

In my env. I log-in to Nextcloud with an IdentityServer. 
It always worked but today I installed the new release version (v2.1.0) of the app and I got this error message:

**"Unable to find a key for (algorithm, kid):RS256, 0DF226FF6ADB5F574473559B11E65B9B)"**

**Comment by emanuel0337** [comment]
Thank you for the update, I was really looking forward to finally using the bearer tokens instead of having a cookie based workaround. Unfortunately I receive a similar error and when checking the stacktrace I found that it originated from the Jumbojett OpenIDConnectClient (verifyJWTsignature). I was not able to fully understand why it fails though. I also use an IdentityServer as SSO provider.

**Comment by JudahMorrison** [comment]
A workaround I am using until this is fixed:

    Download version 2.0.4 locally into your nextcloud server (https://github.com/pulsejet/nextcloud-oidc-login/tags) 
    Replace everything in /var/www/html/custom_apps with the local code except for the ./appinfo folder. (You have to leave the app info folder or else nextcloud will force you to update the app to the latest version.)


The app will look like it is version 2.1.0, but it will actually be 2.0.4 and should work until a new release comes around. I haven't seen any negative side effects or db problems.

**Comment by alesandrino** [comment]
So I have a fix ready. It's basically replacing `strpos($url, "/.well-known/openid-configuration") !== false` with `str_ends_with($url, "/.well-known/openid-configuration") === true`. I know that this is not compatible with php < v8, but this is the best I could come up with.
The problem I have is, that the new level of caching that was introduced with 2.1.0 is very easily broken which results in recursions and out-of-memory errors. I believe this code should receive some more care.
If someone else is willing - this is the branch: https://github.com/alesandrino/nextcloud-oidc-login/tree/fix-integration-with-is
But I do not think that this is ready for a PR.
