### ISSUE TITLE
Login not working with mobile app (android)

### ISSUE THREAD

**Issue by RandomDennisLee** [pulsejet/nextcloud-oidc-login#127]
On the android client, logging in with openid brings up the login screen as expected, but then freezes there and fails to proceed.

Server: Docker, latest version compiled by Linuxserver
Client: Current version
Reverse proxy: Traefik
OIDC provider: Authelia

**Comment by Akruidenberg** [comment]
I'm getting wrong password user. Using Authentik

**Comment by RandomDennisLee** [comment]
I'm afraid my server is no longer running :(

**Comment by azmeuk** [comment]
Ok. We will reopen the ticket if you meet the situation again.
