### ISSUE TITLE
Login after update not possible

### ISSUE THREAD

**Issue by jonathanmmm** [pulsejet/nextcloud-oidc-login#130]
Hi,

I am using nextcloud:stable-fpm docker image, same with nginx in front (also docker).
After an update I saw that ldap config setup didn't work anymore, I updated the nginx config, as suggested (used the official one from nextcloud.com for latest).
Also since the last update I can't login anymore, I am using the same settings from before, haven't changed anything, as far as I know.

This is the error message I get, when I click on the Open ID Login button
The provider authorization_endpoint could not be fetched. Make sure your provider has a well known configuration available.

Is there any way, I can debug this or find something in the logs, maybe in nginx?

Thank you for help

**Comment by quenenni** [comment]
Hello,

Does this link returns something?
https://auth.mydomain.tld/.well-known/openid-configuration

It should be able to access the metadata.

**Comment by jonathanmmm** [comment]
@quenenni No, I am getting 404 - Not found
I am using quay.io/keycloak/keycloak docker image, I have not changed anything since the last time, don't know why it doesn't work anymore.
REDIRECT_SOCKET: "proxy-https"
KEYCLOAK_FRONTEND_URL: https://auth.mydomain.tld/auth

Nginx in the front, I could login via SSO in Element/Matrix/Synapse, so completely broken is it not, I can also login via keycloak admin. But seems to be an keycloak issue then, right?

**Comment by quenenni** [comment]
I'm no expert, but you should have the endpoints available in the well-known configuration.
Nextcloud use it to fetch info.

But, I'm sorry, I'm not using keycloak but LemonLdap.
I don't know how to configure this with keycloak.

**Comment by jonathanmmm** [comment]
@quenenni Ok, so it seems keycloak has this well-known at this position:
`https://auth.mydomain.com/auth/realms/realm-name/.well-known/openid-configuration`
Seems to work now, maybe it needed a slash at the end of 
`'oidc_login_provider_url' => 'https://auth.my-domain.com/auth/realms/realm-name',`
But I removed it and still works, stopped nginx and nextcloud containers, seems to a caching problem maybe?
