### ISSUE TITLE
Support for pkce

### ISSUE THREAD

**Issue by Firstyear** [pulsejet/nextcloud-oidc-login#134]
https://datatracker.ietf.org/doc/html/rfc7636

There are some openid connect providers that required PKCE to function correctly, which it appears that this plugin doesn't support in it's requests. It would be great if this could be updated to have PKCE S256 functionality.

For more: https://medium.com/swlh/pkce-flow-of-openid-connect-9b10ddbabd66

Thanks!

**Comment by azmeuk** [comment]
[PKCE is supported by OpenID-Connect-PHP and implementation should be quite easy](https://github.com/jumbojett/OpenID-Connect-PHP#example-8-pkce-client).

Are you interested in opening a PR?

**Comment by Firstyear** [comment]
I can not code in PHP, so I can not contribute sorry.

**Comment by R0Wi** [comment]
Created a PR for this, please see https://github.com/pulsejet/nextcloud-oidc-login/pull/203
