### ISSUE TITLE
Add support for Nextcloud 23

### ISSUE THREAD

**Issue by dseomn** [pulsejet/nextcloud-oidc-login#146]
It looks like Nextcloud 23 was just released.

**Comment by Starbix** [comment]
After upgrading to Nextcloud 23 and force enabling oidc_login I wasn't able to log in. The site didn't load and returned a `504` after a minute.
In the nginx logs I saw lots of
```
2021/12/02 08:28:54 [error] 44#44: *225 upstream timed out (110: Operation timed out) while reading response header from upstream, client: 2a02:dead::beef, server: , request: "GET /apps/files/ HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock", host: "cloud.example.com"
```

I'm not quite sure why and how, but simply deleting my cookies solved this problem and I was able to login normally using oidc_login and Keycloak.

**Comment by BOZG** [comment]
Since upgrading to 23, Nextcloud has started throwing this error:

`Error The provider authorization_endpoint could not be fetched. Make sure your provider has a well known configuration available.`

I don't see anything strange in the logs and my .well-known configuration is available.

**Comment by Ornias1993** [comment]
@pulsejet This really needs priority.

**Comment by azmeuk** [comment]
Hi. The maintenance of this package is done by the free time of volunteers, independently of the priority of the ongoing issues.
If you want this issue to be fixed soon, the best way you can help is by submitting a pull request.

**Comment by Ornias1993** [comment]
> Hi. The maintenance of this package is done by the free time of volunteers, independently of the priority of the ongoing issues. If you want this issue to be fixed soon, the best way you can help is by submitting a pull request.

Sorry, my time on opensource is not endless.
Nor do I have enough experience with the Nextcloud Codebase.

Even so, completely breaking on a nextcloud update is kinda a no-go, regardless of what the volunteers think about it.

**Comment by dseomn** [comment]
> Even so, completely breaking on a nextcloud update is kinda a no-go, regardless of what the volunteers think about it.

Yes, it's a bad situation. But I don't think imposing additional burden on volunteers for all apps for all upgrades is a feasible solution. And I doubt pressuring them will have any positive effect. On the other hand, I suspect features like https://github.com/nextcloud/updater/issues/401 could avoid a whole bunch of bad situations like this one, with a relatively small one-time effort that helps all apps, and less pressure on volunteers.

**Comment by Ornias1993** [comment]
> > Even so, completely breaking on a nextcloud update is kinda a no-go, regardless of what the volunteers think about it.
> 
> Yes, it's a bad situation. But I don't think imposing additional burden on volunteers for all apps for all upgrades is a feasible solution. And I doubt pressuring them will have any positive effect. On the other hand, I suspect features like [nextcloud/updater#401](https://github.com/nextcloud/updater/issues/401) could avoid a whole bunch of bad situations like this one, with a relatively small one-time effort that helps all apps, and less pressure on volunteers.

Ohh YES PLEASE, that would be a GOD SEND. :-O
As an admin the "randomly disable stuff on update" is an absolute disgusting pain >.<

**Comment by thmo** [comment]
Force-enabling (by setting `max-version="23"` in `appinfo/info.xml`, and running `./occ app:enable oidc_login`) worked for me, the plugin seems to work fine, log-in with the Keycloak account works, nothing remarkable in the logfiles (so far).

**Comment by mkg20001** [comment]
I enabled it regularly via webinterface and things seem to work here aswell. Seems like https://github.com/pulsejet/nextcloud-oidc-login/pull/147 is the way to go.

**Comment by azmeuk** [comment]
v2.2.0 has just been released.
