### ISSUE TITLE
"Error decoding JSON from jwks_uri" because of cache?

### ISSUE THREAD

**Issue by babelouest** [pulsejet/nextcloud-oidc-login#152]
Recently, my OpenID connect had issues, letting oidc_login plugin to get an error 503 when reaching `jwks_uri`.

This problem was fixed since, but it looks like it still uses a cached version of the `jwks_uri` content, because I still have the error "Error decoding JSON from jwks_uri".
I see on the openid connect logs that the `jwks_uri` isn't called.

**Comment by sirkrypt0** [comment]
Thanks for the report! This is indeed an issue, as we cache all responses, regardless of their status code. #156 should fix this. 

Until this is fixed, you can set `oidc_login_public_key_caching_time = 0`  as that will disable returning the cached value. Once your provider is running correctly again and you got a successful response for the JWKs, omit the setting and it will return to its default value (which is 1 day).

**Comment by babelouest** [comment]
Thanks for the fix,

In my case the problem was fixed by itself after a couple of days, so I forgot about it. Thanks for the fix though, this might help with further issues.

But the cache time raises another question, if the server rotates its public keys, they might not be available in nextcloud-oidc-login until the cache expires, therefore making it impossible for users to log in to nextcloud.
I would suggest to log such errors and to add a way to manually clear the cache by an admin, if that's possible.

**Comment by sirkrypt0** [comment]
Yes, key rotation is an issue with plain caching. However, if the key using which a JWT was signed cannot be found in the cache, we ignore the cache and fetch the keys again.

https://github.com/pulsejet/nextcloud-oidc-login/blob/2960523963fbcb00fd2d4260f808bc050d2fe177/lib/Provider/OpenIDConnectClient.php#L69-L86

Clearing the cache is generally possible by setting the corresponding caching time configuration values to `0` (e.g. `oidc_login_public_key_caching_time`) and performing a login afterwards. This approach is not ideal and could be way easier, e.g. with an `occ` command.
