### ISSUE TITLE
Implement Group Mapping with Roles Claim

### ISSUE THREAD

**Issue by DrunkenHusky** [pulsejet/nextcloud-oidc-login#16]
Hi

I am using this plugin with our custom identity provider. Login works fine so far but we would like to use also the group mapping feature as implemented in nextcloud-social-login.

It should be possible, to map the Groups provided by the roles claim to existing Nexctloud Groups, that would be awesome!

Desired Features:
- Mapping of OpenID Roles to NextCloud Roles
- Possibility, to define a default group, which will be auto mapped, if a user gets auto created

Cheers
drunkenhusky

**Comment by pulsejet** [comment]
#33

**Comment by pulsejet** [comment]
Both functionality now present on master

**Comment by DrunkenHusky** [comment]
Hi @pulsejet 
Thank you very much! Happy to test it out :-).

Some questions to the implementation (is maybe important to add to the description/manual):
- Will the Group Mapping overwrite existing Group Mappings? As example: If I add manually groups in Nextcloud to a user and the user logs in via OIDC: Will the plugin overwrite these groups?
- What happens if the array Groups includes values which are not a valid group name? Will all group mappings ignored or just the not matching values? 

Cheers,
Drunkenhusky

**Comment by Excel1** [comment]
Hi @DrunkenHusky :)

>     * Will the Group Mapping overwrite existing Group Mappings? As example: If I add manually groups in Nextcloud to a user and the user logs in via OIDC: Will the plugin overwrite these groups?
- Yes. The User will only have the groups of your OIDC Manager. [(see here)](https://github.com/pulsejet/nextcloud-oidc-login/blob/25592b83a16cd9ea7f186f522f15cab7c760b503/lib/Controller/LoginController.php#L296)

>     * What happens if the array Groups includes values which are not a valid group name? Will all group mappings ignored or just the not matching values?
- It will not just match the values. The mapping will be ignored. [(see here)](https://github.com/pulsejet/nextcloud-oidc-login/blob/25592b83a16cd9ea7f186f522f15cab7c760b503/lib/Controller/LoginController.php#L306)


Full PR: https://github.com/pulsejet/nextcloud-oidc-login/pull/33

Have a great Day!

**Comment by DrunkenHusky** [comment]
Thanks @Excel1 ! Much appreciated :)
