### ISSUE TITLE
How can i get avatar/picture using GitLab OAuth provider?

### ISSUE THREAD

**Issue by KiYiul** [pulsejet/nextcloud-oidc-login#167]
Hello, 

I configure company on-premise GitLab as OAuth provider, and configure Nextcloud OIDC Login plugin to OAuth login.

some config.php information here is,

  'lost_password_link' => 'disabled',
  'hide_login_form' => true,
  'auth.webauthn.enabled' => true,
  ///'oidc_login_provider_url' => 'https://gitlab.company.com/.well-known/openid-configuration',
  'oidc_login_provider_url' => 'https://gitlab.company.com/oauth/userinfo',
  'oidc_login_client_id' => '...',
  'oidc_login_client_secret' => '...',
  'oidc_login_auto_redirect' => true,
  'oidc_login_logout_url' => 'https://nextcloud.company.com',
  'oidc_login_button_text' => 'Log in with GitLab',
  'oidc_login_hide_password_form' => true,
  'oidc_login_attributes' => array (
        'id' => 'sub',
        'name' => 'name',
        'mail' => 'email',
        'photoURL' => 'picture',
        'profile' => 'profile',
  ),
///'oidc_login_default_group' => 'GitLab-OAuth',
  'oidc_login_scope' => 'openid profile email',
  'oidc_login_disable_registration' => false,
  'oidc_login_redir_fallback' => false,
  'oidc_login_update_avatar' => true,

However, I can only view sub, name and email in NextCloud profile menu. How can I get avatar? Is that equal with "picture"?

I have been read reference site as below.
https://docs.gitlab.com/ee/integration/openid_connect_provider.html
https://docs.gitlab.com/ee/integration/oauth_provider.html

and already GitLab OAuth application has been setup to api, openid, profile and email.

**Comment by sirkrypt0** [comment]
Hi 👋 

this feature has been implemented and merged in #165 but has not been released yet.

We are waiting for the owner of this project, @pulsejet ,to publish a new release :)

If you need this feature immediately, you can manually upgrade the plugin by cloning this repo in the corresponding Nextcloud folder.

**Comment by azmeuk** [comment]
v2.3.1 is out!
Can you upgrade and test again @KiYiul?

**Comment by KiYiul** [comment]
Hi @azmeuk
Thanks for your kindly support.

After upgrade to v2.3.1 and re-login with two account on GitLab. One is kiyiul@ is not sync avatar but testaccount@ is synced successfully. 

- How can I trace the OpenID Connect Login plugin?
- When avatar update? at every login?

**Comment by azmeuk** [comment]
The avatar should be updated at every login indeed.
If you enable the [nextcloud debug logs](https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/logging_configuration.html), you should be able to see [this error message](https://github.com/pulsejet/nextcloud-oidc-login/blob/0d0d79b0bb49c9aed205a8666b8a7c9d3c14d07e/lib/Service/LoginService.php#L283) on the logs, and this should help understanding what is going on.

Is kiyiul your gitlab account too? The profile [does not seem to exist](https://gitlab.com/kiyiul).

**Comment by KiYiul** [comment]
Thanks @azmeuk

Here is nextcloud.log in debug mode.

`{"reqId":"YjF1VneKcLqMqn8ce8nb1AAAAMk","level":0,"time":"March 16, 2022 14:27:50","remoteAddr":"...","user":"--","app":"no app in context","method":"GET","url":"/index.php/apps/oidc_login/oidc?code=dd70fe00792c9709102d29b7d87fcca45d6ca004f1b04794bfb7d3c498c18d24&state=fb80f2c871f04c88dc96fcf1e7be46cb","message":"Could not load image for 79 :  Avatar image is not square","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36","version":"23.0.0.10"}`

I doubt avatar/picture must be square belong to "Avatar image is not square" phase. Original picture is jpg format and NOT squared, however I import all employee's photo to each profiles on GitLab successfully.

NextCloud use GitLab as OAuth2 provider and import avatar/picture at every login. but if the avatar/picture in GitLab was NOT squared, then NextCloud can not load the avatar/picture? How can I solve? Is there any alternative way?

**Comment by KiYiul** [comment]
To alternative way, I have been re-wrote bash script of setup employee-photo for GitLab as below.
Point is, resize GitLab account avatar/picture image to square which is 200x200.

`curl -s --header "PRIVATE-TOKEN:$gitlab_token" "$gitlab_url/api/v4/users?per_page=100&order_by=id&sort=asc&page=1" | jq --raw-output '.[] | [.id,.name,.username,.state] | @csv' > 1_table_of_user_1.csv
curl -s --header "PRIVATE-TOKEN:$gitlab_token" "$gitlab_url/api/v4/users?per_page=100&order_by=id&sort=asc&page=2" | jq --raw-output '.[] | [.id,.name,.username,.state] | @csv' > 1_table_of_user_2.csv
cat 1_table_of_user_1.csv 1_table_of_user_2.csv > 1_table_of_user_sum.csv
sed -i '/"blocked"/d' 1_table_of_user_sum.csv
sed -i '/"deactivated"/d' 1_table_of_user_sum.csv
sed -i '/"ldap_blocked"/d' 1_table_of_user_sum.csv

while IFS= read -r line ; do
 gitlab_id=$(echo $line | awk -F',' '{print $1}')
 gitlab_name=$(echo $line | awk -F',' '{print $2}')
 gitlab_username=$(echo $line | awk -F',' '{print $3}')
 gitlab_state=$(echo $line | awk -F',' '{print $4}')
 employee_id=$(cat "$path_AD_attribute" | grep "$gitlab_username" | awk -F',' '{print $2}' | head -n 1 | sed 's/"//g')

 echo $gitlab_id, $gitlab_name, $gitlab_username, $employee_id

 convert -define jpeg:size=200x200 "$path_images_src"/"$employee_id".jpg -thumbnail '100x100>' -gravity center -background transparent -extent 100x100 "$path_images_tgt"/"$employee_id".jpg

 curl --request PUT --header "PRIVATE-TOKEN:$gitlab_token" --form "avatar=@""$path_images_tgt""/""$employee_id"".jpg" "$gitlab_url"/api/v4/users/"$gitlab_id"

done < 1_table_of_user_sum.csv`

Thanks @azmeuk
