### ISSUE TITLE
Keyclock X redirect page not found

### ISSUE THREAD

**Issue by arozmarin** [pulsejet/nextcloud-oidc-login#169]
Hi guys,

I"m testing new keyclick 17 and new redirect url is different than old, new url 'https://keycloak.example.com/realms/YOUR_REALM'
old url 'https://keycloak.example.com/auth/realms/YOUR_REALM'. that means new keyclick don't have 'auth' in url. I change url in config but Nextcloud still redirect to old URL. 
I tried to disable "OpenID Connect Login" and back enable, remove and reinstall and also reboot server and nothing helped. 

Where or how  should I change url that will be redirect to new URL.

thanks

**Comment by Whhoesj** [comment]
I bumped into the same issue today.

It looks like this plugin caches the .well-known page in the database.
Removing the rows containing `last_updated_well_known` and `well-known` from the `oc_appconfig` table in the database solves it.

Hopefully #157 will prevent this problem in the future.

**Comment by arozmarin** [comment]
thanks for info, I manage to fix too.

**Comment by trensetim** [comment]
the provided workaround works. But I would really like to see an occ action like "maintenance:update-oidc-wellknown" or something alike

**Comment by trensetim** [comment]
managed it by doing

docker exec -it nextcloud-postgres psql -U nextcloud
`delete from oc_appconfig where appid='oidc_login' and (configkey='well-known' or configkey='last_updated_well_known');`

**Comment by azmeuk** [comment]
I close this ticket because there is already #157
