### ISSUE TITLE
Support OpenID Connect RP-Initiated Logout

### ISSUE THREAD

**Issue by hschletz** [pulsejet/nextcloud-oidc-login#171]
Keycloak 18 removed support for the redirect_uri URL parameter out of the box which this app uses for the oidc_login_logout_url option.

As a temporary workaround, Keycloak can be started with spi-login-protocol-openid-connect-legacy-logout-redirect-uri=true, but that option will probably be removed in Keycloak 21.

More info in the release announcement: https://www.keycloak.org/2022/04/keycloak-1800-released

**Comment by jonathanmmm** [comment]
could this already been included with https://github.com/pulsejet/nextcloud-oidc-login/pull/117?
Couldn't get it to work, but haven't tried every possible config that I can think of.

**Comment by jonathanmmm** [comment]
Would maybe need a new variable to set it to redirect to nextcloud back directly, maybe as a boolean or a string https://github.com/pulsejet/nextcloud-oidc-login/pull/117#discussion_r867278929

**Comment by jonathanmmm** [comment]
@hschletz https://github.com/pulsejet/nextcloud-oidc-login/pull/174 please try changing your `config.php` like described here and tell me if it works for you aswell.

**Comment by hschletz** [comment]
Yes, it works, also without the workaround mentioned above. Thanks a lot!
