### ISSUE TITLE
Broken plugin for NC 24.0

### ISSUE THREAD

**Issue by Skiepp** [pulsejet/nextcloud-oidc-login#172]
Starting from NC 24 the `DefaultTokenProvider` class is removed from private namespace, generating the error:

> Could not resolve OC\Authentication\Token\DefaultTokenProvider! Class "OC\Authentication\Token\DefaultTokenProvider" does not exist

This makes the plugin not working on NC 24.

Related issue: https://github.com/nextcloud/server/issues/29914

**Comment by flo-mic** [comment]
Have the same issue unfortunately

**Comment by vfiuchcikicshuusrch** [comment]
Have the same issue unfortunately

**Comment by Ornias1993** [comment]
To be fair this has been depricated since nextcloud 13(!)
https://github.com/nextcloud/server/pull/30016

**Comment by thmo** [comment]
Are there any short-term workarounds?

**Comment by hakoerber** [comment]
I have a workaround: Replace `DefaultTokenProvider` by `PublicKeyTokenProvider` in `lib/Service/LoginService.php`:

```diff
diff --git i/lib/Service/LoginService.php w/lib/Service/LoginService.php
index 80aed9c9..213d9d6a 100644
--- i/lib/Service/LoginService.php
+++ w/lib/Service/LoginService.php
@@ -2,7 +2,7 @@

 namespace OCA\OIDCLogin\Service;

-use OC\Authentication\Token\DefaultTokenProvider;
+use OC\Authentication\Token\PublicKeyTokenProvider;
 use OC\User\LoginException;
 use OCA\OIDCLogin\Provider\OpenIDConnectClient;
 use OCP\IAvatarManager;
@@ -373,7 +373,7 @@ class LoginService
             $userSession->getSession()->regenerateId();
         }

-        $tokenProvider = \OC::$server->query(DefaultTokenProvider::class);
+        $tokenProvider = \OC::$server->query(PublicKeyTokenProvider::class);
         $userSession->setTokenProvider($tokenProvider);
         $userSession->createSessionToken($request, $user->getUID(), $user->getUID());
         $token = $tokenProvider->getToken($userSession->getSession()->getId());
```

After that, OIDC login works again.

**Disclaimer**: I have **absolutely no clue** whether that is actually safe. It might completely break authentication.

**Comment by thmo** [comment]
Ok, I tried this, also seems to work (but I also **dont't have any clue**):
```patch
--- LoginService.php.orig	2022-05-07 16:41:25.099918258 +0200
+++ LoginService.php	2022-05-07 16:42:12.984702551 +0200
@@ -2,7 +2,7 @@
 
 namespace OCA\OIDCLogin\Service;
 
-use OC\Authentication\Token\DefaultTokenProvider;
+/* use OC\Authentication\Token\DefaultTokenProvider; */
 use OC\User\LoginException;
 use OCA\OIDCLogin\Provider\OpenIDConnectClient;
 use OCP\IAvatarManager;
@@ -373,7 +373,7 @@
             $userSession->getSession()->regenerateId();
         }
 
-        $tokenProvider = \OC::$server->query(DefaultTokenProvider::class);
+        $tokenProvider = \OC::$server->query('OC\Authentication\Token\IProvider');
         $userSession->setTokenProvider($tokenProvider);
         $userSession->createSessionToken($request, $user->getUID(), $user->getUID());
         $token = $tokenProvider->getToken($userSession->getSession()->getId());


```

**Comment by vfiuchcikicshuusrch** [comment]
@hakoerber thank you, this works for me too.
still waiting official fix.

**Comment by sirkrypt0** [comment]
Hey :wave: 

sorry for the inconvenience! I implemented a fix in #173 that uses the `IProvider` instead of the `DefaultTokenProvider`, similar to what @thmo used as a workaround.  
This now awaits a review and once merged we'll need to wait until @pulsejet releases a new version. Hope to get this shipped ASAP!

**Comment by pulsejet** [comment]
Please test with v2.3.2

**Comment by thmo** [comment]
Looks good, thanks!
