### ISSUE TITLE
Unable to determine state

### ISSUE THREAD

**Issue by HannesJo0139** [pulsejet/nextcloud-oidc-login#181]
Hi,

running Nextcloud (linuxserver.io docker image) with OIDC Login and Authelia behind SWAG reverse proxy, I sometimes get that error page right after login.
`Unable to determine state`

Nextcloud log has nothing but in the proxy (nginx) access log I can find:
```
<ip> - - [14/Jun/2022:15:20:10 +0200] "GET /apps/oidc_login/oidc HTTP/1.1" 302 5 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:101.0) Gecko/20100101 Firefox/101.0"
.
.
<ip> - - [14/Jun/2022:15:20:28 +0200] "GET /authelia/api/oidc/authorization?client_id=...&nonce=...&redirect_uri=https%3A%2F%2Fcloud.wilmaw.org%2Fapps%2Foidc_login%2Foidc&response_type=code&scope=...&state=... HTTP/2.0" 303 0 "https://wilmaw.org/authelia/2fa/one-time-password" "Mozilla/5.0 (X11; Linux x86_64; rv:101.0) Gecko/20100101 Firefox/101.0"
<ip> - nextcloud [14/Jun/2022:15:20:28 +0200] "POST /authelia/api/oidc/token HTTP/2.0" 200 1261 "-" "-"
<ip> - - [14/Jun/2022:15:20:28 +0200] "GET /apps/oidc_login/oidc?code=...&scope=...&state=8cb1a75df9ee3dbb56686080760da980 HTTP/2.0" 500 3831 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:101.0) Gecko/20100101 Firefox/101.0"

```

The last line clearly shows the request with passed state variable ending up in HTTP500 (Nextcloud shows the error)

**Comment by HannesJo0139** [comment]
Sometimes issues are being resolved by time :D It was a provider problem.

**Comment by tna76874** [comment]
Since today I suddenly do not manage to login via oidc. Nextcloud shows: "Unable to determine state"

restored the database from two days ago including the oidc_login app 2.4.1. ---> same error

Since yesterday I did not update the NC - only the oidc_login plugin to 2.5.0.

Keycloak shows the error:
`keycloak_1  | 05:58:56,224 WARN  [org.keycloak.events] (default task-11) type=LOGIN_ERROR, realmId=[deleted], clientId=[deleted], userId=null, ipAddress=[deleted], error=user_not_found, auth_method=openid-connect, grant_type=password, client_auth_method=client-secret, username=[deleted], authSessionParentId=[deleted], authSessionTabId=[deleted]`

Has somebody an idea how I can resolve this issue ??

**Comment by Reinitialized** [comment]
@HannesJo0139 @tna76874 Are/were you two using Firefox by chance? Firefox is the browser I daily drive, but came across [this comment on issue 61](https://github.com/pulsejet/nextcloud-oidc-login/issues/61#issuecomment-751587393) . This resulted in me testing it in Microsoft Edge, which I do not experience this issue with and confirmed everything works fine, so curious if it affects others.

For clarity sake, I am running Firefox 102.12.0esr (64-bit) on Windows 11 [Version 10.0.22621.1928]

**Comment by tna76874** [comment]
Actually it turned out to be Redis to cause this error. This affected every login (local or oidc). So nothing to blame the oidc login app here :)

**Comment by Reinitialized** [comment]
> Actually it turned out to be Redis to cause this error. This affected every login (local or oidc). So nothing to blame the oidc login app here :)

Would you mind explaining what allowed you to identify the culprit to be Redis? From container logs, I do not see any output suggesting even the lightest of issues.

**Comment by tna76874** [comment]
Actually it took me quite a time to figure out the problem. In detail I did not track down what caused the error. But maybe it was a combination of maintenance mode for backups + swichting summer/winter time in this period. I disnanteled the whole setup. After removing redis, everything worked again fine. After 2 months of mystery-solving journey.

**Comment by HannesJo0139** [comment]
I still see the error every 2 or three months. My common Browser is Chrome. Gonna try removing redis..

**Comment by tna76874** [comment]
Removing redis might not be the best solution. if tracked down to redis, it might be reasonable to identify the problem. In this case it is a nextcloud issue and not a oidc-issue.

**Comment by Reinitialized** [comment]
How is your Disk IO? I am running Nextcloud on my own hardware under Proxmox + some old spinny bois, and I notice this seems to happen more when IO Delay starts creeping up during heavy demand
