### ISSUE TITLE
Undefined index: REQUEST_METHOD in CLI

### ISSUE THREAD

**Issue by aszlig** [pulsejet/nextcloud-oidc-login#19]
When installing the app (or any app followed by installing `oidc_login`) a warning is emitted about [`$_SERVER['REQUEST_METHOD']`](https://github.com/pulsejet/nextcloud-oidc-login/blob/74e7d4dc6ef0cdcdb7eeec0ff8e5f094a64e750e/lib/AppInfo/Application.php#L82) being not defined.

Since there is no such index when running in command line, it might be a good idea to either test whether currently running in `occ` or simply coalesce the index lookup to some sane default.

Here is a full CI log of how this manifests:

https://headcounter.org/hydra/log/59c0jyqd1wh3566r89aipf355lla7m6k-vm-test-run-nextcloud-upgrade.drv

Note that the final error here is completely unrelated to `oidc_login`, it's just to illustrate that the [`register()`](https://github.com/pulsejet/nextcloud-oidc-login/blob/74e7d4dc6ef0cdcdb7eeec0ff8e5f094a64e750e/lib/AppInfo/Application.php#L30) method is called every time *any* app is enabled/disabled.

**Comment by pulsejet** [comment]
Fixed by #19
