### ISSUE TITLE
White screen: no login

### ISSUE THREAD

**Issue by joshp23** [pulsejet/nextcloud-oidc-login#2]
Using NextCloud 16.0.6 with nginx on an ubuntu 18.04 server with all updates.

I tried to set this up with keycloak. Here's my config:
```
// OIDC BEGIN
	'allow_user_to_change_display_name' => false, 
	'lost_password_link' => 'disabled',
	'oidc_login_provider_url' => 'https://keycloak.example.com/auth/realms/master', 
	'oidc_login_client_id' => 'NextCloud', 
	'oidc_login_client_secret' => 'super-secret-hash-for-client', 
	'oidc_login_auto_redirect' => false, 
	'oidc_login_logout_url' => 'https://nextcloud.example.com/', 
	'oidc_login_default_quota' => '1000000', 
	'oidc_login_button_text' => 'Log in with OpenID', 
	'oidc_login_attributes' => array ( 
            'id' => 'sub',
            'name' => 'name',
            'uid' => 'sub',
            'mail' => 'mail',
            'quota' => 'ownCloudQuota',
            'home' => 'homeDirectory',
	),
// OIDC END
```
When logging in, it directs to keycloak just fine when clicking the "Login with OpenID" button. It logs in fine, and then redirects back to nextcloud's base url. This results in white screen and the following error:
```
"message":"Undefined index: uid at \/var\/www\/nextcloud\/apps\/oidc_login\/lib\/Controller\/LoginController.php#169"
```
if I add ` 'id_alt' => 'sub',` to `'oidc_login_attributes'` there is a white screen with no error in the log.

**Comment by pulsejet** [comment]
Try setting `oidc_login_disable_registration` to `false` maybe? Creating new users is disabled by default. I'll also be removing the `id_alt` part shortly (just slipped in into the final code by mistake)

**Comment by joshp23** [comment]
that worked, but I'm not wanting to register new clients. How do I map the OIDC login to existing users? In keycloak, there is the `username` attribute. I tried to set 
```
'oidc_login_attributes' => array ( 
		'id' => 'username',
).
```
and it failed.

**Comment by pulsejet** [comment]
@joshp23 what backend are your existing users on? If they are in the plain nextcloud users backend, then it should work as long as the username field exists in the keycloak user response exists. Try setting debug to true to see what is failing. Also, id is hashed only when it is bigger than 64 characters IIRC, so it should pick up username properly if it is present in the response.

**Comment by joshp23** [comment]
>what backend are your existing users on

The plain nexcloud users backend.

>it should work as long as the username field exists in the keycloak user response

It does, here's an example response from KeyCloak when requesting user info
```
{
    "access": {
        "impersonate": true,
        "manage": true,
        "manageGroupMembership": true,
        "mapRoles": true,
        "view": true
    },
    "attributes": {
        "id_alt": [
            "joshp23"
        ],
        "uname": [
            "joshp23"
        ]
    },
    "createdTimestamp": 1572810618700,
    "disableableCredentialTypes": [
        "password"
    ],
    "email": "user@domain.com",
    "emailVerified": true,
    "enabled": true,
    "firstName": "EXAMPLE",
    "id": "some-fancy-hash-from-keycloak",
    "lastName": "EXAMPLE",
    "notBefore": 0,
    "requiredActions": [],
    "totp": false,
    "username": "joshp23"
}

```
>Try setting debug to true to see what is failing.

Already on.

**Comment by joshp23** [comment]
Found the required value for `id` in Keycloak. It is `preferred_username`. Thank you for you assistance.
