### ISSUE TITLE
Exception after upgrade to oidc_login 2.4.0: syntax error, unexpected 'AttributeMap'

### ISSUE THREAD

**Issue by njunike** [pulsejet/nextcloud-oidc-login#205]
After an upgrade to oidc_login 2.4.0 the following exception is raised when user tries to login via web-ui:

    {
        "reqId": "2vthkYKVj02zt4K7LuD4",
        "level": 3,
        "time": "2022-11-28T09:45:45+00:00",
        "remoteAddr": "********",
        "user": "--",
        "app": "index",
        "method": "GET",
        "url": "/apps/oidc_login/oidc",
        "message": "syntax error, unexpected 'AttributeMap' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST)",
        "userAgent": "Mozilla/5.0 (X11; Linux x86_64; rv:107.0) Gecko/20100101 Firefox/107.0",
        "version": "23.0.11.1",
        "exception": {
            "Exception": "ParseError",
            "Message": "syntax error, unexpected 'AttributeMap' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST)",
            "Code": 0,
            "Trace": [
            {
                "file": "/var/www/nextcloud/lib/composer/composer/ClassLoader.php",
                "line": 428,
                "function": "Composer\\Autoload\\includeFile",
                "args": [
                "/var/www/nextcloud/apps/oidc_login/lib//Service/LoginService.php"
                ]
            },
            {
                "function": "loadClass",
                "class": "Composer\\Autoload\\ClassLoader",
                "type": "->",
                "args": [
                "OCA\\OIDCLogin\\Service\\LoginService"
                ]
            },
            {
                "function": "spl_autoload_call",
                "args": [
                "OCA\\OIDCLogin\\Service\\LoginService"
                ]
            },
            {
                "file": "/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php",
                "line": 112,
                "function": "__construct",
                "class": "ReflectionClass",
                "type": "->",
                "args": [
                "OCA\\OIDCLogin\\Service\\LoginService"
                ]
            },
            {
                "file": "/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php",
                "line": 131,
                "function": "resolve",
                "class": "OC\\AppFramework\\Utility\\SimpleContainer",
                "type": "->",
                "args": [
                "OCA\\OIDCLogin\\Service\\LoginService"
                ]
            },
            {
                "file": "/var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php",
                "line": 463,
                "function": "query",
                "class": "OC\\AppFramework\\Utility\\SimpleContainer",
                "type": "->",
                "args": [
                "OCA\\OIDCLogin\\Service\\LoginService"
                ]
            },
            {
                "file": "/var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php",
                "line": 435,
                "function": "queryNoFallback",
                "class": "OC\\AppFramework\\DependencyInjection\\DIContainer",
                "type": "->",
                "args": [
                "OCA\\OIDCLogin\\Service\\LoginService"
                ]
            },
            {
                "file": "/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php",
                "line": 87,
                "function": "query",
                "class": "OC\\AppFramework\\DependencyInjection\\DIContainer",
                "type": "->",
                "args": [
                "OCA\\OIDCLogin\\Service\\LoginService",
                true
                ]
            },
            {
                "function": "OC\\AppFramework\\Utility\\{closure}",
                "class": "OC\\AppFramework\\Utility\\SimpleContainer",
                "type": "->",
                "args": [
                "*** sensitive parameters replaced ***"
                ]
            },
            {
                "file": "/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php",
                "line": 106,
                "function": "array_map",
                "args": [
                {
                    "__class__": "Closure"
                },
                [
                    {
                    "__class__": "ReflectionParameter",
                    "name": "appName"
                    },
                    {
                    "__class__": "ReflectionParameter",
                    "name": "request"
                    },
                    {
                    "__class__": "ReflectionParameter",
                    "name": "config"
                    },
                    {
                    "__class__": "ReflectionParameter",
                    "name": "urlGenerator"
                    },
                    {
                    "__class__": "ReflectionParameter",
                    "name": "userManager"
                    },
                    "And 6 more entries, set log level to debug to see all entries"
                ]
                ]
            },
            {
                "file": "/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php",
                "line": 114,
                "function": "buildClass",
                "class": "OC\\AppFramework\\Utility\\SimpleContainer",
                "type": "->",
                "args": [
                {
                    "__class__": "ReflectionClass",
                    "name": "OCA\\OIDCLogin\\Controller\\LoginController"
                }
                ]
            },
            {
                "file": "/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php",
                "line": 131,
                "function": "resolve",
                "class": "OC\\AppFramework\\Utility\\SimpleContainer",
                "type": "->",
                "args": [
                "OCA\\OIDCLogin\\Controller\\LoginController"
                ]
            },
            {
                "file": "/var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php",
                "line": 463,
                "function": "query",
                "class": "OC\\AppFramework\\Utility\\SimpleContainer",
                "type": "->",
                "args": [
                "OCA\\OIDCLogin\\Controller\\LoginController"
                ]
            },
            {
                "file": "/var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php",
                "line": 435,
                "function": "queryNoFallback",
                "class": "OC\\AppFramework\\DependencyInjection\\DIContainer",
                "type": "->",
                "args": [
                "OCA\\OIDCLogin\\Controller\\LoginController"
                ]
            },
            {
                "file": "/var/www/nextcloud/lib/private/AppFramework/App.php",
                "line": 144,
                "function": "query",
                "class": "OC\\AppFramework\\DependencyInjection\\DIContainer",
                "type": "->",
                "args": [
                "OCA\\OIDCLogin\\Controller\\LoginController"
                ]
            },
            {
                "file": "/var/www/nextcloud/lib/private/Route/Router.php",
                "line": 302,
                "function": "main",
                "class": "OC\\AppFramework\\App",
                "type": "::",
                "args": [
                "OCA\\OIDCLogin\\Controller\\LoginController",
                "oidc",
                {
                    "__class__": "OC\\AppFramework\\DependencyInjection\\DIContainer"
                },
                [
                    "oidc_login.login.oidc"
                ]
                ]
            },
            {
                "file": "/var/www/nextcloud/lib/base.php",
                "line": 1015,
                "function": "match",
                "class": "OC\\Route\\Router",
                "type": "->",
                "args": [
                "/apps/oidc_login/oidc"
                ]
            },
            {
                "file": "/var/www/nextcloud/index.php",
                "line": 36,
                "function": "handleRequest",
                "class": "OC",
                "type": "::",
                "args": []
            }
            ],
            "File": "/var/www/nextcloud/apps/oidc_login/lib/Service/LoginService.php",
            "Line": 51,
            "CustomMessage": "--"
        }
    }

A revert back to oidc_login 2.3.3 solved the issue:

- login via ssh to server
- cd to nextcloud dir
- disable oidc_login app (e.g. `sudo -u www-data php occ app:disable oidc_login`)
- replace folder nexcloud/apps/oidc_login by  oidc_login.tar.gz  from [2.3.3-release](https://github.com/pulsejet/nextcloud-oidc-login/releases/tag/v2.3.3)
- enable oidc_login app (e.g. `sudo -u www-data php occ app:enable oidc_login`)

**Comment by pulsejet** [comment]
PHP version?

**Comment by njunike** [comment]
PHP 7.3.31-1~deb10u1 (debian buster)

**Comment by pulsejet** [comment]
PHP 7.3 EOL a year ago. You need 7.4 or later for 2.4.0+

**Comment by njunike** [comment]
Ok, thanks for looking into this! I will update PHP.

Based on [Nextcloud 23 requirements](https://docs.nextcloud.com/server/23/admin_manual/installation/system_requirements.html) where PHP 7.3 is listed as compatible, I was assuming, this is also true for all "Nextcloud 23 compatible" apps.
