### ISSUE TITLE
Issue : password create in nextcloud database for OpenId connect users

### ISSUE THREAD

**Issue by mathsyx69** [pulsejet/nextcloud-oidc-login#207]
Hello,

I have a nextcloud instance installed and I use your application to connect with AzureAD.
I encourtered an error sometime when a new employee register on nextcloud (account create at first azureAd connection).

He got a error message which demand that the password contain special character.
I don't understand how your app work with the password of accounts create with OpenID Connect.

I have two simple question:
What happens to the field password in the nextcloud database ? 
It this a bug that you already met ?

Thank by advance for your help.

Have a good day.

**Comment by pulsejet** [comment]
A random password is generated for each user. We should be including a fixed string at the start containing some special characters so it satisfies the password policies.

https://github.com/pulsejet/nextcloud-oidc-login/blob/dc101a70029872c95b298ea8efb7daa7bb8e7764/lib/Service/LoginService.php#L271

**Comment by mathsyx-fr** [comment]
Thank for the response. To resolve this bug I delete this line (271) and replace it with : 

$randomPassword = substr(base64_encode(random_bytes(64)), 0, 28);
$userPassword = ":" . $randomPassword . "["; 

It could be interesting to add a correction in a next update.

**Comment by pulsejet** [comment]
Please don't close this until it's fixed. If possible it'd be great if you could do a PR for this. Ideally we can just prepend the password with something like `aA1$` which could cover all cases.
