### ISSUE TITLE
Curl error: (3) 

### ISSUE THREAD

**Issue by deeztek** [pulsejet/nextcloud-oidc-login#209]
Hello, 

Trying to get OIDC to work with Nextcloud version 25.0.1. Configured the config.php as per the docs. The OpenID Connect button appears but as soon as I click it I get Curl error: (3). The URL for the button is:

https://cloud.domain.tld/apps/oidc_login/oidc

Is there an issue with the OpenID Connect Login app with this version of Nextcloud?

thanks in advance

**Comment by pulsejet** [comment]
This is some misconfiguration. What did you set `oidc_login_provider_url` to?

**Comment by deeztek** [comment]
I have set the oidc_login_provider_url to my authentication provider, in this case Authelia to https://auth.domain.tld. If by avatars you mean the oidc_login_update_avatar line, no that's set to false. Here's the config:

```
array (
    'allow_user_to_change_display_name' => false,
    'lost_password_link' => 'disabled',
    'oidc_login_provider_url' => 'https://auth.domain.tld',
    'oidc_login_client_id' => 'nextcloud',
    'oidc_login_client_secret' => 'super_secret_client_secret',
    'oidc_login_auto_redirect' => false,
    'oidc_login_end_session_redirect' => false,
    'oidc_login_button_text' => 'Log in OAuth2',
    'oidc_login_hide_password_form' => false,
    'oidc_login_use_id_token' => true,
    'oidc_login_attributes' => array (
        'id' => 'preferred_username',
        'name' => 'name',
        'mail' => 'email',
        'groups' => 'groups',
    ),
    'oidc_login_default_group' => 'oidc',
    'oidc_login_use_external_storage' => false,
    'oidc_login_scope' => 'openid profile email groups',
    'oidc_login_proxy_ldap' => false,
    'oidc_login_disable_registration' => true,
    'oidc_login_redir_fallback' => false,
    'oidc_login_alt_login_page' => 'assets/login.php',
    'oidc_login_tls_verify' => true,
    'oidc_create_groups' => false,
    'oidc_login_webdav_enabled' => false,
    'oidc_login_password_authentication' => false,
    'oidc_login_public_key_caching_time' => 86400,
    'oidc_login_min_time_between_jwks_requests' => 10,
    'oidc_login_well_known_caching_time' => 86400,
    'oidc_login_update_avatar' => false,
);
```

**Comment by pulsejet** [comment]
Does turning on debug give any stack trace?

**Comment by deeztek** [comment]
This may be something of interest from the logs:

```
{"reqId":"azCMipF3KECPh6bczXFd","level":0,"time":"2022-12-13T12:30:41+00:00","remoteAddr":"192.168.xxx.xxx","user":"--","app":"carnet","method":"GET","url":"/apps/oidc_login/oidc","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:102.0) Gecko/20100101 Firefox/102.0","version":"25.0.2.3","data":{"app":"carnet"}}

{"reqId":"azCMipF3KECPh6bczXFd","level":0,"time":"2022-12-13T12:30:41+00:00","remoteAddr":"192.168.xxx.xxx","user":"--","app":"drawio","method":"GET","url":"/apps/oidc_login/oidc","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:102.0) Gecko/20100101 Firefox/102.0","version":"25.0.2.3","data":{"app":"drawio"}}
```

Is it possible that it has a problem with the drawio and the carnet apps?

**Comment by deeztek** [comment]
Not getting anything in the logs besides a 500 error but no indication on what the problem actually is.

**Comment by Borega** [comment]
I have the exact same problem. Did u find a solution?

**Comment by deeztek** [comment]
I haven't found a solution but I haven't messed with it since either. Do you also have draw.io and carnet on your instance?

**Comment by ASLLR** [comment]
Hi everyone, 

i've the same issue with Nextcloud v24.0.9. I think none of config is supported, because the option "oidc_login_button_text" not changed the button. I use the same config than deeztek.

Best Regards

**Comment by lazerleif** [comment]
Hey, i have the same problem and did also noticed that the login button didnt change text accordingly to the settings.

I have Nextcloud 24.0.5

**Comment by Codename-11** [comment]
Same issue...

**Comment by deeztek** [comment]
Got it working with Authelia. I'm on NC 26.0.2. I also had it working on 25.0.7. Ensure the **oidc_login_client_secret** field in NC config.php is the same as the **secret** field in Authelia configuration.yml. Additionally, ensure that the **oidc_login_client_id** in NC config.php is the same as the **id** field in Authelia configuration.yml file. Of course the oidc_login_provider_url would the URL of your Authelia server and the redirect_uris will be the URL of your NC server. 

Here's the NC config.php:

  **'allow_local_remote_servers' => true,
  'encryption.legacy_format_support' => true,
  'encryption.key_storage_migrated' => false,
  'allow_user_to_change_display_name' => false,
  'lost_password_link' => 'disabled',
  'oidc_login_provider_url' => 'https://auth.domain.tld',
  'oidc_login_client_id' => 'my-nextcloud',
  'oidc_login_client_secret' => 'super_secret_clent_secret_string',
  'oidc_login_auto_redirect' => false,
  'oidc_login_end_session_redirect' => false,
  'oidc_login_button_text' => 'Log in with oidc',
  'oidc_login_hide_password_form' => false,
  'oidc_login_use_id_token' => true,
  'oidc_login_attributes' =>
  array (
    'id' => 'preferred_username',
    'name' => 'name',
    'mail' => 'email',
    'groups' => 'groups',
  ),
  'oidc_login_default_group' => 'oidc',
  'oidc_login_use_external_storage' => false,
  'oidc_login_scope' => 'openid profile email groups',
  'oidc_login_proxy_ldap' => false,
  'oidc_login_disable_registration' => false,
  'oidc_login_redir_fallback' => false,
  'oidc_login_alt_login_page' => 'assets/login.php',
  'oidc_login_tls_verify' => true,
  'oidc_create_groups' => true,
  'oidc_login_webdav_enabled' => false,
  'oidc_login_password_authentication' => false,
  'oidc_login_public_key_caching_time' => 86400,
  'oidc_login_min_time_between_jwks_requests' => 10,
  'oidc_login_well_known_caching_time' => 86400,
  'oidc_login_update_avatar' => false,**

Here's the Authelia config:

      **- id: my-nextcloud
        description: Deeztek NextCloud
        secret: 'super_secret_clent_secret_string'
        public: false
        authorization_policy: two_factor
        redirect_uris:
          - https://cloud.domain.tld/apps/oidc_login/oidc
        scopes:
          - openid
          - profile
          - email
          - groups
        userinfo_signing_algorithm: none**

**Comment by kekersdev** [comment]
Had the same issue. The problem was caused by a typo in `oidc_login_logout_url`

**Comment by deeztek** [comment]
I didn't generate the password with the method you outlined above. I created a 64-character alphanumeric random string and I plugged it in on the **oidc_login_client_secret** on the Nextcloud side and on **secret** on the Authelia side. You can use the following command to create a random string using openssl:

`/usr/bin/openssl rand -hex 64`
