### ISSUE TITLE
Missing jwks breaks the login

### ISSUE THREAD

**Issue by avionbg** [pulsejet/nextcloud-oidc-login#21]
I'm using glewlwyd as openId provider, and under token encryption I have JWT type SHA 512 bit. Problem is that this kind of key doesn't allow jwks keys, or at least thats stated in their documentation - https://babelouest.github.io/glewlwyd/docs/OIDC.html under JWKS explanation.
It would be nice to handle this case since I can't provide other type of tokens due to some limitation in other clients in the network.

**Comment by pulsejet** [comment]
Can't be very sure, but AFAIK a JWKS file is needed in the "official" OIDC call flow. Anyway, this is an issue you'll need to raise at the client library that we're using for OIDC authorization (https://github.com/jumbojett/OpenID-Connect-PHP)
