### ISSUE TITLE
Keycloak Display Name with Firstname Lastname not set

### ISSUE THREAD

**Issue by mueller-tobias** [pulsejet/nextcloud-oidc-login#212]
I'm using Keycloak 20.0.1 with Nextcloud 25.0.2 with the oidc_login 2.4.0.

We're not able to set the correct display name with keycloak. I can use 

```
            'oidc_login_attributes' => array (
                'id' => 'sub',
                'name' => 'given_name',
                'mail' => 'email',
            ),
```
or
```
            'oidc_login_attributes' => array (
                'id' => 'sub',
                'name' => 'family_name',
                'mail' => 'email',
            ),
```

And the correct values from keycloak are used as display name. The problem is i can't get the concat from `family_name` and `given_name` working.

With `"${given_name} ${family_name}"` i'll get the following error:

```
Warning: Undefined variable $given_name in /var/www/html/config/openid.config.php on line 91

Warning: Undefined variable $family_name in /var/www/html/config/openid.config.php on line 91
Config file has leading content, please remove everything before "<?php" in openid.config.php
Fatal error: Uncaught Error: Call to a member function getLogger() on null in /var/www/html/index.php:71 Stack trace: #0 {main} thrown in /var/www/html/index.php on line 71
```

What's the correct syntax to concat `family_name` and `given_name`.

**Comment by pulsejet** [comment]
You can't. The attribute map has to refer to individual fields.

**Comment by TobiasMuellerES** [comment]
Ok. Thanks!

As a workaround i used the full name mapper in keycloak to get a field with a combined first and last name.
Maybe you can edit the [README.md](https://github.com/pulsejet/nextcloud-oidc-login/blame/master/README.md#L104) and Remove the hint to that kind of configuration.

In the examples you've listed the combination of given_name and family_name for keycloak.
