### ISSUE TITLE
Question concerning 'oidc_login_auto_redirect', security-implications

### ISSUE THREAD

**Issue by ZID-TU-Graz** [pulsejet/nextcloud-oidc-login#218]
Hello,

we are currently using the `oidc_login_auto_redirect => true` setting for a specific IP range only, which works very well. A given set of users see the "Username/Password" page, others get automatically redirected to our OIDC Provider.

Question is: Is ist still possible to forcefully login via Username/password", as one would by using the login page? 
Or does the code flow guarantee that after enabling  `oidc_login_auto_redirect => true` no other methods are available/active?

We need to implement a rather strict 2FA policy for users outside a given IP range, so we have to make sure nobody is able to circument OIDC-login by forecfully using the username/password login form post method.

Thank You.

**Comment by pulsejet** [comment]
Currently you can always log in using password simply by adding `?noredir=1` to the login URL.

**Comment by ZID-TU-Graz** [comment]
Hello,

ok, thank you for this information - did not know this parameter.
