### ISSUE TITLE
Why does the default claim mapper use 'mail' and not 'email'?

### ISSUE THREAD

**Issue by sbrudenell** [pulsejet/nextcloud-oidc-login#23]
I know I can map the 'email' claim, but I was curious why oidc_login looks for a claim named 'mail' by default. Per https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims , it seems like 'email' is the standard for this.

The default logic blanked out my email address the first time I logged in, so I was confused.

**Comment by pulsejet** [comment]
Haha nice point. The sponsorer of this project currently uses a custom
provider that provides the 'mail' attribute. Keeping this open for now;
I'll change it to 'email' once I ascertain it won't break anything there.

**Comment by pulsejet** [comment]
Changed. Thanks @sbrudenell!
