### ISSUE TITLE
Can't access settings

### ISSUE THREAD

**Issue by ccgauvin94** [pulsejet/nextcloud-oidc-login#241]
My understanding is that after installing the app, there should be a settings menu. However, none appears, even after restarting NextCloud.  

![image](https://github.com/pulsejet/nextcloud-oidc-login/assets/17997344/aeaea43c-c0a4-4df0-ab69-befa08921fd2)

Running 27.0.2 in a docker container.

**Comment by pulsejet** [comment]
There isn't one. You configure everything using `config.php` (see readme)

**Comment by ccgauvin94** [comment]
Thanks

**Comment by rgruenewald** [comment]
Is there any chance / plan to configure the app via the admin panel? I'm on a managed nextcloud without access to the config.php

**Comment by pulsejet** [comment]
Plan? No. The project is open to PRs though.
