### ISSUE TITLE
Usage of Core function unavailable on NC26 branch (ITimeFactory)

### ISSUE THREAD

**Issue by Insektaure** [pulsejet/nextcloud-oidc-login#253]
Hi,

since the 3.0.0 update, oidc_login makes a call to an unavailable Nextcloud Core function on v26.

In lib/Controller/LoginController.php :

`$this->session->set('last-password-confirm', \OC::$server->get(ITimeFactory::class)->now());`

This now() function is available since 27.0 beta1 which make this new update incompatible with NC v26 branches (doesn't seems to have been backported).

It triggers the following error :

"Message":"Call to undefined method OC\\AppFramework\\Utility\\TimeFactory::now() in file 'oidc_login/lib/Controller/LoginController.php' line 109"

In this case, shouldn't this version only be made available only for NC v27 & up ?

**Comment by pulsejet** [comment]
Hotfix in 3.0.1
