### ISSUE TITLE
OpenIDConnectClient name already in use

### ISSUE THREAD

**Issue by ThumbGen** [pulsejet/nextcloud-oidc-login#260]
I am successfully using a NC 27 derived custom image, with oidc-plugin 2.6.0, in a kubernetes cluster.
The app is manually copied to /usr/src/nextcloud/apps in my image.
Now I've updated to NC 28 and copied the oidc-plugin 3.0.2 in /usr/src/nextcloud/apps.

Nextcloud seems to be updated successfully yet the plugin (?) is throwing this error and I can't authenticate using oidc anymore.
The oidc_login 3.0.2 app appears as 'enabled' in Nextcloud.

`2024-01-12T15:32:22.680632500Z [Fri Jan 12 15:32:22.679877 2024] [php:error] [pid 701] [client 192.168.65.3:0] PHP Fatal error:  Cannot declare class OCA\\OIDCLogin\\Provider\\OpenIDConnectClient because the name is already in use in /var/www/html/apps/oidc_login/lib/Provider/OpenIDConnectClient.php on line 12`

Any idea what could cause this?

PS: The error happens also without updating Nextcloud, using directly a NC28 / oidc_login 3.0.2 combination

**Comment by pulsejet** [comment]
NEver seen thsi before, could be a cache issue. Did you try a reboot?

**Comment by ThumbGen** [comment]
I think that I know what happens. I removed the app I was copying to /usr/src/nextcloud/apps and I enable now the oidc_login app from store. I guess there were 2 apps registered at the same time? Did NC28 suddenly include oidc_login by default?
