### ISSUE TITLE
Could not boot oidc_login

### ISSUE THREAD

**Issue by AkshayRao27** [pulsejet/nextcloud-oidc-login#268]
Yesterday, my Nextcloud desktop client stopped syncing, I could not upload files through the browser, and my App list was completely blank. When I checked the error log, it was full of these two errors going as far back as I could possibly go. Disabling the plugin made everything work perfectly again.

Throughout this time, I have been able to log in with Authelia using the plugin and sync was working fine. Something changed in the past few days that caused things to break, and I have no idea what. I'm not sure if this is a bug or a config issue on my end. What other info can I provide that would help diagnose what is going on here?

Level: `Fatal`
Application: `no app in context`
Message:
```
Error Failed opening required 'assets/login.php' (include_path='/var/www/nextcloud/3rdparty/pear/archive_tar:/var/www/nextcloud/3rdparty/pear/console_getopt:/var/www/nextcloud/3rdparty/pear/pear-core-minimal/src:/var/www/nextcloud/3rdparty/pear/pear_exception:/var/www/nextcloud/apps')
Could not boot oidc_login: Failed opening required 'assets/login.php' (include_path='/var/www/nextcloud/3rdparty/pear/archive_tar:/var/www/nextcloud/3rdparty/pear/console_getopt:/var/www/nextcloud/3rdparty/pear/pear-core-minimal/src:/var/www/nextcloud/3rdparty/pear/pear_exception:/var/www/nextcloud/apps')
```
Level: `Error`
Application: `PHP`
Message:
```
require(assets/login.php): Failed to open stream: No such file or directory at /var/www/nextcloud/apps/oidc_login/lib/AppInfo/Application.php#152
```

Version: Nextcloud Hub 7 (28.0.3)
Operating System: TurnKey GNU/Linux 18.0 (Debian 12/Bookworm)
Hosting Method: LXC Container in Proxmox (VE 8.1.4)
Config File: https://pastebin.com/LViS1aV7 

![image](https://github.com/pulsejet/nextcloud-oidc-login/assets/44117116/6cf42d18-4aad-48ef-9784-16ac606b1a82)
![image](https://github.com/pulsejet/nextcloud-oidc-login/assets/44117116/fb3219fe-3f56-498d-839b-22480a323e34)

**Comment by pulsejet** [comment]
Remove `oidc_login_alt_login_page` from your config file

**Comment by keesfluitman** [comment]
@pulsejet That didn't work for me. Got the same error

`Fatal | no app in context | Error Failed  opening required 'assets/login.php'  (include_path='/app/www/public/3rdparty/pear/archive_tar:/app/www/public/3rdparty/pear/console_getopt:/app/www/public/3rdparty/pear/pear-core-minimal/src:/app/www/public/3rdparty/pear/pear_exception:/app/www/public/apps')  Could not boot oidc_login: Failed opening required 'assets/login.php'  (include_path='/app/www/public/3rdparty/pear/archive_tar:/app/www/public/3rdparty/pear/console_getopt:/app/www/public/3rdparty/pear/pear-core-minimal/src:/app/www/public/3rdparty/pear/pear_exception:/app/www/public/apps')
`

**Comment by pulsejet** [comment]
@keesfluitman restart the PHP server after you change config.php

**Comment by keesfluitman** [comment]
> @keesfluitman restart the PHP server after you change config.php

I rebooted the entire container, to no effect yet. Ill check further.

**Comment by keesfluitman** [comment]
@pulsejet 
Shall i open a new bug report or is there some support forum perhaps?

**Comment by pulsejet** [comment]
Not sure, there's really nothing to fix here. If you see `Application.php`, it checks for `oidc_login_alt_login_page` in the config and tries to require it on line 152 (where you get the error) if set. So the only way you could get this error is when this key is defined (and set to `assets/login.php`) in your config.

https://github.com/pulsejet/nextcloud-oidc-login/blob/49e2be6a02290f295938aefad17bfdc525ef3d67/lib/AppInfo/Application.php#L74

https://github.com/pulsejet/nextcloud-oidc-login/blob/49e2be6a02290f295938aefad17bfdc525ef3d67/lib/AppInfo/Application.php#L147-L155

**Comment by keesfluitman** [comment]
thanks. that made me realize the settings were set twice in my config files. And they actually were...both in config.php and my oidc.config.php had all values in it. 
Dunno why oidc_login_hide_password_form has no effect yet though.

**Comment by pulsejet** [comment]
That's probably broken now, it was just a css hack

**Comment by keesfluitman** [comment]
> That's probably broken now, it was just a css hack

ye i just did it myself manually now. thanks again for your quick replies. like a pro company ;).
