### ISSUE TITLE
[Feature] Flatten Profile-Array

### ISSUE THREAD

**Issue by jit-reisacherm** [pulsejet/nextcloud-oidc-login#27]
Hi

I am using this plugin with the Apereo CAS, which returns a multi-dimensional array after a successful login. Thus, the `$profile` variable looks something like that:

```php
$profile = [
    id,
    default_group    
    sub,
    auth_time,
    attributes: [
        aid,
        naid,
        preferred_username,
        scp,
        uid <--- That's what I need!
    ],
]
```

It would be great to have the possibility to flatten the `$profile`-array before extracting information like `$ldapUid` or `$uid`!

Cheers,
Matt

**Comment by pulsejet** [comment]
This should not be too difficult to achieve. Since we support only top level attributes, might as well make this default, by flattening this to something like
```php
$profile = [
    id,
    default_group    
    sub,
    auth_time,
    attributes_aid,
    attributes_naid,
    attributes_preferred_username,
    attributes_scp,
    attributes_uid
]
```

**Comment by pulsejet** [comment]
Should be available in the next release
