### ISSUE TITLE
v3.0.2 not activable in NextCloud Hub 8 / NextCloud 29

### ISSUE THREAD

**Issue by WoBuGs** [pulsejet/nextcloud-oidc-login#277]
Through the NextCloud app store UI, it is not possible to enable the extension after migrating to NextCloud 29, due to the application manifest specifying NextCloud 28 as the maximum supported version: https://github.com/pulsejet/nextcloud-oidc-login/blob/v3.0.2/appinfo/info.xml#L32

Note: it works if when forcing through the `occ` CLI:

```bash
occ app:enable --force oidc_login
```

I guess this issue will close naturally with the next release.

**Comment by pulsejet** [comment]
https://github.com/pulsejet/nextcloud-oidc-login/releases/tag/v3.1.0
