### ISSUE TITLE
White screen with 3.1.0 update 

### ISSUE THREAD

**Issue by lukas-staab** [pulsejet/nextcloud-oidc-login#278]
Hi i got a white screen of death with the newly 3.1.0 update (instead of external login screen). Due to it being a production enviroment I could not debug further, but I can have a look into the logs if no one else is able to reproduce it. I will update acordingly. 

Tested with php8.1 and 8.2, NC v27.1.8

What I have done to downgrade: (Maybe it helps others)

* disable app with:  php occ app:disable oidc_login
* delete v3.1.0 oidc_login folder in /apps/ 
* Download v3.0.2, (with `wget https://github.com/pulsejet/nextcloud-oidc-login/releases/download/v3.0.2/oidc_login.tar.gz` )  unpack it ( `tar -xvzf oidc_login.tar.gz` ) and copy it in /apps/ 
* Enable App again php occ app:enable oidc_login

After Downgrade it worked again as it should

**Comment by lukas-staab** [comment]
Here is the relevant Logged Error: 

``` 
	Cannot declare class OCA\OIDCLogin\Provider\OpenIDConnectClient because the name is already in use at ~/nextcloud/apps/oidc_login/lib/Provider/OpenIDConnectClient.php#12
```

Here is a list of the installed apps if relevant: 

```
  - activity: 2.19.0
  - admin_audit: 1.17.0
  - announcementcenter: 6.8.1
  - bbb: 2.6.0
  - bookmarks: 13.1.3
  - bruteforcesettings: 2.7.0
  - calendar: 4.7.2
  - cloud_federation_api: 1.10.0
  - comments: 1.17.0
  - contacts: 5.5.3
  - contactsinteraction: 1.8.0
  - dav: 1.27.0
  - deck: 1.11.4
  - drawio: 2.1.4
  - external: 5.2.1
  - federatedfilesharing: 1.17.0
  - federation: 1.17.0
  - files: 1.22.0
  - files_accesscontrol: 1.17.1
  - files_automatedtagging: 1.17.0
  - files_linkeditor: 1.1.20
  - files_markdown: 2.4.1
  - files_mindmap: 0.0.30
  - files_pdfviewer: 2.8.0
  - files_reminders: 1.0.0
  - files_rightclick: 1.6.0
  - files_sharing: 1.19.0
  - files_texteditor: 2.15.1
  - files_trashbin: 1.17.0
  - files_versions: 1.20.0
  - files_zip: 1.4.1
  - forms: 3.4.7
  - group_default_quota: 0.1.7
  - groupfolders: 15.3.7
  - groupquota: 0.1.13
  - login_notes: 1.3.1
  - logreader: 2.12.0
  - lookup_server_connector: 1.15.0
  - maps: 1.2.0
  - notifications: 2.15.0
  - oauth2: 1.15.2
  - oidc_login: 3.0.2
  - photos: 2.3.0
  - polls: 5.4.3
  - privacy: 1.11.0
  - provisioning_api: 1.17.0
  - quicknotes: 0.8.10
  - quota_warning: 1.19.0
  - recommendations: 1.6.0
  - related_resources: 1.2.0
  - richdocuments: 8.2.9
  - serverinfo: 1.17.0
  - settings: 1.9.0
  - sharebymail: 1.17.0
  - support: 1.10.1
  - systemtags: 1.17.0
  - tasks: 0.15.0
  - terms_of_service: 2.3.1
  - text: 3.8.0
  - theming: 2.2.0
  - twofactor_backupcodes: 1.16.0
  - twofactor_totp: 9.0.0
  - twofactor_webauthn: 1.4.0
  - updatenotification: 1.17.0
  - user_ldap: 1.17.0
  - viewer: 2.1.0
  - workflowengine: 2.9.0
Disabled:
  - afterlogic: 2.0.10 (installed 2.0.10)
  - analytics: 4.13.0 (installed 4.13.0)
  - apporder: 0.15.0 (installed 0.15.0)
  - auto_groups: 1.5.3 (installed 1.5.3)
  - circles: 27.0.1 (installed 27.0.1)
  - dashboard: 7.7.0 (installed 7.4.0)
  - encryption: 2.15.0
  - files_external: 1.19.0
  - firstrunwizard: 2.16.0 (installed 2.13.0)
  - gpxpod: 5.0.13 (installed 5.0.13)
  - news: 24.0.0 (installed 24.0.0)
  - nextcloud_announcements: 1.16.0 (installed 1.13.0)
  - onlyoffice: 9.2.0 (installed 9.2.0)
  - passman: 2.4.9 (installed 2.4.9)
  - password_policy: 1.17.0 (installed 1.14.0)
  - survey_client: 1.15.0 (installed 1.12.0)
  - suspicious_login: 5.0.0
  - user_external: 3.3.0 (installed 3.3.0)
  - user_saml: 5.2.7 (installed 5.2.7)
  - user_status: 1.7.0 (installed 1.4.0)
  - weather_status: 1.7.0 (installed 1.4.0)
```

**Comment by MonsieurPono** [comment]
Same here:

After an upgrade to version 3.1, the login page is blank and these record appears in Nextcloud log files:

[PHP] Erreur: Cannot declare class OCA\OIDCLogin\Provider\OpenIDConnectClient because the name is already in use at /data/www/nextcloud/apps/oidc_login/lib/Provider/OpenIDConnectClient.php#12
GET /apps/oidc_login/oidc
de XXXXXXXX par -- à 4 mai 2024 à 11:08:38

Tested with PHP 8.2 and 8.3, Nextcloud 28.0.5.1

Please let me know if you need additional information.

**Comment by pulsejet** [comment]
Restart PHP server

**Comment by MonsieurPono** [comment]
> Restart PHP server

Restarted and rebooted but same error.

**Comment by MaxWaldorf** [comment]
Same issue here, int he logs I have:
`Cannot declare class OCA\OIDCLogin\Provider\OpenIDConnectClient because the name is already in use at /var/www/html/custom_apps/oidc_login/lib/Provider/OpenIDConnectClient.php#12`

Had to downgrade...

**Comment by tna76874** [comment]
I confirm the error message. Setup with docker. A restart did not solve the error.

**Comment by pulsejet** [comment]
Please try v3.1.1 (this patch https://github.com/pulsejet/nextcloud-oidc-login/commit/2d2de767e056eaae6d0c78f6eb420f438a5f2d64)

**Comment by lukas-staab** [comment]
3.1.1 solved the problem. Thanks for the very fast patch!
