### ISSUE TITLE
User Quota Being reset

### ISSUE THREAD

**Issue by joshp23** [pulsejet/nextcloud-oidc-login#3]
Using the default value of
`'quota' => 'ownCloudQuota',`
the user data quota is reset to 997 Kb. How do I set this per user since it is in the config?

**Comment by joshp23** [comment]
Solved: 
1. In Keycloak, I created the user attribute `ownCloudQuota` 
2. I set the above value to reflect each user's data limit already stored in Nextcloud. 
3. I created an `ownCloudQuota` in the `Mapper` section of the keycloak nextcloud client, mapping to the user attribute above.

**Comment by pulsejet** [comment]
@joshp23 great to hear that things are working out! Could you make a PR to update the README with brief general instructions on how you proceeded to integrate keycloak with this app if you have some time to spare?
