### ISSUE TITLE
Can't login using Keycloak

### ISSUE THREAD

**Issue by TomCranitch** [pulsejet/nextcloud-oidc-login#31]
Hi. I have attempted to configure this using keycloak. However, when logging in the following error message is logged and the user is redirected to the login screen.

`[PHP] Error: First parameter must either be an object or the name of an existing class at /var/www/nextcloud/apps/oidc_login/3rdparty/jumbojett/openid-connect-php/src/OpenIDConnectClient.php#284`

```
  'oidc_login_client_id' => 'CLIENT_ID',
  'oidc_login_client_secret' => 'CLIENT_SECRET',
  'oidc_login_provider_url' => 'URL',
  'oidc_login_auto_redirect' => true,
  'oidc_login_redir_fallback' => true,
  'oidc_login_logout_url' => 'REDIRECT_URL',
  'oidc_login_attributes' => array(
    'id' => 'preferred_username',
    'mail' => 'email',
  ),
  'oidc_login_tls_verify' => false,
  'oidc_login_default_quota' => '1000000',
```

Any ideas what the issue could be? Thanks!

**Comment by pulsejet** [comment]
Are you sure Keycloak is configured correctly for OIDC (and working without other applications say)? If I understand correctly, this means Keycloak is returning no token on it's token API.

**Comment by TomCranitch** [comment]
Thanks for pointing me in the right direction. It looks like keycloak was causing the issue.

**Comment by MohMehrnia** [comment]
I set this setting for fusionauth but can not show login page and logout page page is ok

**Comment by pulsejet** [comment]
What error do you get @MohMehrnia?

**Comment by MohMehrnia** [comment]
Not show any error, but can not redirect to openid loginpage

**Comment by pulsejet** [comment]
Check the logs please. The information you provided is not sufficient.
