### ISSUE TITLE
not working with calendars and addressbooks

### ISSUE THREAD

**Issue by quenenni** [pulsejet/nextcloud-oidc-login#36]
I tested with the nextcloud-client and it works beautifully with our Nextcloud / keycloak.

But when I try to configure a calendar in Thunderbird, it asks for the login / passwd but doesn't recognize / accept it and ask again.

Are the calendars / addressbooks not using the same authorization process as an access to the web interface?

Do you know if it's suppose to work?

Thanks

**Comment by RoelReijn** [comment]
You can use app passwords for that:

The App Password is an alternative password with which various APIs and, for example, contacts / calendar applications work. An App Password has the same rights as your regular password, so protect this password well.

1. Go to the Nextcloud settings by pressing your profile picture in the online cloud environment and clicking the “Settings” button.
2. Select Security in the left menu.
3. Scroll down to the Devices section.
4. Enter a recognizable name in the “App name” field.
5. Press Create new app password.
6. The password will be shown **once**. Copy or save the password.
7. Use the App Password in your application, in this case Thunderbird.

**Comment by quenenni** [comment]
@RoelReijn 

Amazing! Thanks a lot.
I never used that feature.

So, it doesn't use the SSO, but as calendars / address books configured in Thunderbird don't really need to use the sso, I'm happy with that.

Thanks again for sharing.

**Comment by pulsejet** [comment]
Thunderbird doesn't have support for OAuth in my knowledge, so this is an issue on their side. As suggested, you will have to generate app specific passwords.

**Comment by kosssi** [comment]
I don't understand but when I would like generate app token Nextcloud ask me a password, but I never create password on Nextcloud for this user. It's connect with OIDC.

Have you a suggestion ?
