### ISSUE TITLE
New user crash when External Storage is disabled

### ISSUE THREAD

**Issue by rickfleming** [pulsejet/nextcloud-oidc-login#38]
When a new OIDC user who attempts to login to NextCloud via version 1.4 of this plugin, when "External Storage" app is disabled through Apps, the plugin crashes with the following:

"Internal Server Error"
"The server was unable to complete your request..."

In the logs the following exists:

OCP\AppFramework\QueryException: Could not resolve storagesService! Class storagesService does not exist/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php - line 115:OC\AppFramework\Utility\SimpleContainer->resolve("storagesService")/var/www/html/lib/private/ServerContainer.php - line 150:OC\AppFramework\Utility\SimpleContainer->query("storagesService", true)/var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php - line 389:OC\ServerContainer->query("storagesService", true)/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php - line 70:OC\AppFramework\DependencyInjection\DIContainer->query("storagesService", true)/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php - line 100:OC\AppFramework\Utility\SimpleContainer->buildClass(ReflectionCl ... "})/var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php - line 115:OC\AppFramework\Utility\SimpleContainer->resolve("OCA\\OIDCLo ... r")
--

I believe it was introduced by this pull request: #32

**Comment by pulsejet** [comment]
Very strange; I had tested this myself. What version of NC is this?

**Comment by rickfleming** [comment]
18.0.4, using the official docker image:

https://hub.docker.com/_/nextcloud/

**Comment by pulsejet** [comment]
Just tried, can't repro on the same docker image. Are you sure everything is configured right?
