### ISSUE TITLE
Authorizing requests to Nextcloud with access token 

### ISSUE THREAD

**Issue by michzimny** [pulsejet/nextcloud-oidc-login#47]
Hi,
thanks to nextcloud-oidc-login, I can log in into my Nextcloud via an OIDC provider. In addition, I'd like to have another app (OIDC client) that would make HTTP requests to Nextcloud on behalf of a user. 

The app gets a user's OAuth2 access token from the OIDC and sends requests to Nextcloud with header: `Authorization: Bearer $TOKEN`. The requests are not authorized by Nextcloud though.

Example request & response:

```
GET /apps/files/ HTTP/1.1
Authorization: Bearer eyJhbG...
...

HTTP/1.1 401 Unauthorized
Content-Length: 43
Content-Type: application/json; charset=utf-8
...

{
    "message": "Current user is not logged in"
}
```

Should this work? Do I do this incorrectly? Or is it not implemented? If the latter, is it a use case related to nextcloud-oidc-login or it's rather out of scope?

Thank you in advance!

**Comment by pulsejet** [comment]
Shouldn't be related to nextcloud-oidc-login. AFAIK even the desktop app does this and it works just fine.

**Comment by michzimny** [comment]
Thanks for prompt reply.

AFAIK the desktop app uses [that oAuth setup](https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/oauth2.html) which means that Nextcloud itself acts as OIDC authorization server, i.e. it issues and validates access tokens. It's not what I'm thinking of.

I'm looking for a solution that the OIDC authorization server that is used with nextcloud-oidc-login for the log-in process (i.e. in your app) is also used to validate access tokens of any other HTTP requests, incoming to Nextcloud.

Are you aware of any existing solution for this?

**Comment by pulsejet** [comment]
Ahh okay, I misunderstood. I don't think that really fits in the scope of
this plugin, as we're concerned mainly about authenticating the user to
nextcloud here, but I'll definitely consider any PR that implement this.

**Comment by torshid** [comment]
@pulsejet the PR is here https://github.com/pulsejet/nextcloud-oidc-login/pull/99, would be really great if you can review it and merge it :)
