### ISSUE TITLE
Default login method

### ISSUE THREAD

**Issue by joshp23** [pulsejet/nextcloud-oidc-login#5]
Is there a way to make OIDC login the default method, maybe using the Nextcloud login as fallback in case of failure?

**Comment by pulsejet** [comment]
Well, you can set `oidc_login_auto_redirect` to `true` and it will automatically redirect the login page to your provider. Is this what you're looking for? AFAIK there's no real way to disable the password login with a public Nextcloud API.

**Comment by joshp23** [comment]
Does `oidc_login_auto_redirect` fallback to Nextcloud in the event of failure?

**Comment by joshp23** [comment]
Also, with `oidc_login_auto_redirect => true` and `oidc_login_logout_url => cloud.example.com`, when I log out of Nextcloud it redirects to Keycloak, where I am still logged in(?), and so it is not possible to log out of Nextcloud. I changed `oidc_login_logout_url => https://keycloak.example.com/auth/realms/MY_REALM/protocol/openid-connect/logout`, but this just hangs on a blank page. There is no redirect back to anything desirable. The logout URL would need to be triggered while redirecting the browser to login. Am I missing something from this end? I looked in Keycloak, not finding a solution yet.

**Comment by pulsejet** [comment]
Yeah, basically you need a third page to direct logged out users to. With `v1.1.0` you should automatically get redirected to NextCloud's login page on logout if you have enabled auto-redirection and not specified a logout URL. Also, setting `oidc_login_redir_fallback` to `true` will fall back to password login on failing to login with OIDC, with the caveat that no error message will be displayed.

**Comment by joshp23** [comment]
Solution to avoid Keycloak white screen after logout = send a redirect URI to Keycloak with the logout:
```
oidc_login_auto_redirect => true
oidc_login_redir_fallback => true
oidc_login_logout_url => https://keycloak.example.com/auth/realms/MY_REALM/protocol/openid-connect/logout?redirect_uri=https%3A%2F%2Fcloud.example.com%2F
```
