### ISSUE TITLE
allow manually adding groups in nextcloud

### ISSUE THREAD

**Issue by Nyeksenn** [pulsejet/nextcloud-oidc-login#51]
Hi,

I have Nextcloud deployed alongside Gitlab and I am using this plugin to authenticate users with Gitlab as the OIDC Provider.
In my setup it is necessary to be able to add users to groups manually in nextcloud and they need to survive a relogin.
In the current state of the plugin groups that are not in the groups array from the OIDC Provider get removed.
I understand why this is but it would be great if there were a settings option like 

`'oidc_allow_manual_groups => true,`

to enable this.
I have currently solved this by commenting out the appropriate lines but this is of course not a good solution.
I think adding an if around the code section would suffice. Something like:
```
// Remove user from groups not present
if (!$this->config->getSystemValue('oidc_allow_manual_groups', false)) {
    $currentUserGroups = $this->groupManager->getUserGroups($user);
    foreach ($currentUserGroups as $currentUserGroup) {
        if (!in_array($currentUserGroup->getDisplayName(), $groupNames)) {
	    $currentUserGroup->removeUser($user);
	}
    }
}
```

I can create a pull request if this is something you would consider pulling.

**Comment by pulsejet** [comment]
This is intentional behavior; there is supposed to be only a single point of "truth" in the philosophy of this plugin, which can be either Nextcloud or the OIDC provider in this case.
