### ISSUE TITLE
Auto create new groups from OIDC

### ISSUE THREAD

**Issue by marcopalumbo** [pulsejet/nextcloud-oidc-login#55]
I'm settng up NC with Keycloack as ID provider, the only thing I see missing (I beg your pardon if it does exist but i've not seen it) that could be really useful in my use case.
Basically I'd like to have the groups that are listed in the userinfo coming OIDC to be automatically created in NC, actually the users are added to groups only if groups are already existing.

If I'm missing an already present feature let me know

**Comment by pascal1337** [comment]
+1

We also need a feature like this

**Comment by d-vo** [comment]
Added PR here https://github.com/pulsejet/nextcloud-oidc-login/pull/73

**Comment by pulsejet** [comment]
Merged

**Comment by marcopalumbo** [comment]
Great! Thanks @d-vo !
@pulsejet are you going to release a newer version containing all the new commits since 1.6.1?
Thanks again

**Comment by pulsejet** [comment]
@marcopalumbo yup will do that in a couple of days probably.

**Comment by marcopalumbo** [comment]
hey @pulsejet far from me the intention of bothering you on this issue, by now I implemented the feature by manually editing the file and works perfectly, Just to know if you have a planned date for the release

**Comment by pulsejet** [comment]
So sorry I totally forgot about this. v1.7.0 is up on the store now.
