### ISSUE TITLE
OpenID profile partial mapping

### ISSUE THREAD

**Issue by bpresles** [pulsejet/nextcloud-oidc-login#57]
My OpenID provider (Unikname) is privacy oriented and so doesn't return much information of the user (userinfo), only the following:

```json
{
    "sub":"hgBSa9tHIFfRhMyfNiNlx8ko_7SFAc_7L5Xa91ZOex4",
    "auth_time":1602855803,
    "id":"hgBSa9tHIFfRhMyfNiNlx8ko_7SFAc_7L5Xa91ZOex4"
}
```

When I use it with the Nextcloud OpenID Connect Login plugin, the user fullname is filled by the "sub" value. If I try to specify a partial mapping (because there is no "name" information) like this:

```php
'oidc_login_attributes' => array (
        'id' => 'sub',
  )
```

The user's fullname is still filled with the "sub" value. I also tried to put 'name' => null, without any improvement.

Also if I change the values via Nextcloud's user profile form of the fullname but even of the email, the value is overwritten at next login by "sub" for the fullname and nothing (blank) for the email.

How can I make sure that :

1. The sub doesn't fill the fullname value at login ?
2. The values personalized through the Nextcloud's user profile form are kept ?

Version of the plugin used: 1.6.1 (latest on Nextcloud store).

Thank you in advance.

**Comment by pulsejet** [comment]
You'll need to add a check to not set display name if the `name` attribute is explicitly set to null. If you don't intend to make a PR, just comment out this line https://github.com/pulsejet/nextcloud-oidc-login/blob/247355bf00b74f583cb2771328d3f737d8c5d69a/lib/Controller/LoginController.php#L278

**Comment by bpresles** [comment]
Ok, thank you for your answer, I'll make a PR then ;)
