### ISSUE TITLE
nginx rewrite oidc url

### ISSUE THREAD

**Issue by daydrim** [pulsejet/nextcloud-oidc-login#61]
Hello!

With nginx + php-fpm [configuration](https://docs.nextcloud.com/server/latest/admin_manual/installation/nginx.html) - Nginx rewrites URL and redirect back to:

`nextcloud/login?noredir=1`

in nginx access.log:

`"GET /nextcloud/apps/oidc_login/oidc HTTP/2.0" 302 0 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0"`

**Comment by daydrim** [comment]
The problem is in rewrites configuration.
So there is an option in NextCloud docs 

[nextcloud manual](https://docs.nextcloud.com/server/latest/admin_manual/installation/nginx.html)

So for nextcloud-oidc-login

`cgi.fix_pathinfo` must be set to `0`
`cgi.fix_pathinfo=0`

**Comment by daydrim** [comment]
It helps only with GET and Redirect

However when we return via callback url we've returned again to
`nextcloud/login?noredir=1`

**Comment by pulsejet** [comment]
Is `oidc_login_redir_fallback` is to true? Can you try turning it to false if yes?

**Comment by daydrim** [comment]
Hello ! It seems it resolves the problem with redirection !) Thanx

However we recieved the following error in most of the sessions:
[Unable to determine state](https://github.com/jumbojett/OpenID-Connect-PHP/issues/93)

**Comment by pulsejet** [comment]
Is the state query parameter present?

**Comment by azmeuk** [comment]
I am closing for now. Please feel free to reopen the issue if you still face it.
