### ISSUE TITLE
limit to group/role?

### ISSUE THREAD

**Issue by r2evans** [pulsejet/nextcloud-oidc-login#69]
I'm migrating from an LDAP realm to an SSO realm, and I'm looking at both keycloak and gluu. For both OpenID IdP, the notion of limiting a user's access to a specific client/SP by group (or role) is argued to be a topic of *authorization* (vice OIDC's *authentication*), and therefore the responsibility of the SP.

Is it possible to limit the use of NC by the presence of groups or roles in the user's attributes?

**Comment by pulsejet** [comment]
Ideally you should do this on the provider side. But I'll be happy to review any PRs to implement this too.

**Comment by sirkrypt0** [comment]
Hey,

we use Keycloak and face this issue a lot. However, it is possible to accomplish this without the app but solely with Keycloak. Have a look at [this plugin](https://github.com/giz-berlin/keycloak-role-authenticator) in which we implemented it.
