### ISSUE TITLE
How to use this to connect to a Gluu server?

### ISSUE THREAD

**Issue by noromamai** [pulsejet/nextcloud-oidc-login#7]
Am new to OpenID en Gluu. I would like my Nextcloud (17) server to authenticate against a Gluu server (not using their oxd thing), but am not sure how to set up the configurations on both sides. Would appreciate help and pointers if someone has managed to set this up before already. I read documentation, but did not give me a clear enough picture to be able to set it up.

**Comment by pulsejet** [comment]
Hi @noromamai 
I haven't used Gluu, but as long as you can configure it to provide the logged in user's info after authentication, you should be able to use this plugin. What you need to do in brief is:
1) Figure out the base URL of the OIDC provider (Gluu in this case). The endpoints other than this will be figured out using `.well-known`
2) Get the relevant keys from the returned user response and configure them in this app. For example, if Gluu returns the following user response:
```json
{
    "name": "Foo",
    "username": "bar",
    "emailid": "foobar@mymail.com"
}
```
then your configuration entry would look something like
```php
'oidc_login_attributes' => array (
    'id' => 'username',
    'name' => 'name',
    'mail' => 'emailid',
)
```

**Comment by noromamai** [comment]
i never got it to work with gluu and then found out gluu only does authentication and no authorization so i went with keycloak.

**Comment by pulsejet** [comment]
Ah, I see
