### ISSUE TITLE
Login from keycloak overwrites Nextcloud display name

### ISSUE THREAD

**Issue by shibacomputer** [pulsejet/nextcloud-oidc-login#70]
I've set up a passwordless authentication pipeline where users authenticate against Nextcloud via an identity provider within Keycloak. Users can change their display names, but upon the next login the display name is reset to the value stored inside Keycloak. 

My `config.php` is straightforward, and I'm setting `allow_user_to_change_display_name` as per the README: 
```
  'allow_user_to_change_display_name' => true,
  'oidc_login_provider_url' => 'https://xxx/auth/realms/xxx,
  'oidc_login_client_id' => 'xxx',
  'oidc_login_client_secret' => 'xxxxx',
  'oidc_login_attributes' =>
  array (
    'id' => 'sub',
    'name' => 'preferred_username',
    'mail' => 'email',
  ),
  'oidc_login_scope' => 'openid profile email',
  ```

Despite this setup, the OIDC plugin overwrites the user's name with Keycloak's `preferred_username` every time they log in. Am I missing something?

**Comment by shibacomputer** [comment]
As a small update, logging in voa Keycloak and OIDC will also reset user quotas to the default, even if they've been modified within Nextcloud.

**Comment by pulsejet** [comment]
This is intended behavior. The OIDC store is considered the single point of truth, and users/admins are not supposed to modify values in the nextcloud db.
