### ISSUE TITLE
Installation instructions insufficient

### ISSUE THREAD

**Issue by hwellmann** [pulsejet/nextcloud-oidc-login#74]
I've tried following the README to install this app in Nextcloud to login via Keycloak.

I can't make it work, and I don't even see the OpenId button in the login screen, and no error messages anywhere.

I'm now using the `user_oidc` app which works out of the box.

**Comment by pulsejet** [comment]
If you see no openid button, it means the app isn't enabled. What version of NC is this?
Also there may be errors in your log. IIRC Nextcloud automatically turns off apps that don't bootstrap correctly.

**Comment by intelligentops** [comment]
Hello @hwellmann @pulsejet 
I also don't see the button, because the app is disabled. Nextcloud throws exception when I press 'enable'. It's a clean Nextcloud in docker setup. Could you help me please?

Nextcloud version 20.0.7.1

nextcloud.log

> {"reqId":"Ps0BqFs7KqpAKTsqip1h","level":3,"time":"2021-03-01T11:47:20+00:00","remoteAddr":"172.19.0.3","user":"admin","app":"no app in context","method":"GET","url":"/apps/files","message":{"Exception":"OCP\\AutoloadNotAllowedException","Message":"Autoload path not allowed: /var/www/html/apps/files_external/lib/service/globalstoragesservice.php","Code":0,"Trace":[{"file":"/var/www/html/lib/autoloader.php","line":165,"function":"isValidPath","class":"OC\\Autoloader","type":"->","args":["/var/www/html/apps/files_external/lib/service/globalstoragesservice.php"]},{"function":"load","class":"OC\\Autoloader","type":"->","args":["OCA\\Files_External\\Service\\GlobalStoragesService"]},{"function":"spl_autoload_call","args":["OCA\\Files_External\\Service\\GlobalStoragesService"]},{"file":"/var/www/html/custom_apps/oidc_login/lib/AppInfo/Application.php","line":42,"function":"class_exists","args":["\\OCA\\Files_External\\Service\\GlobalStoragesService"]},{"file":"/var/www/html/custom_apps/oidc_login/appinfo/app.php","line":6,"function":"register","class":"OCA\\OIDCLogin\\AppInfo\\Application","type":"->","args":[]},{"file":"/var/www/html/lib/private/legacy/OC_App.php","line":289,"args":["/var/www/html/custom_apps/oidc_login/appinfo/app.php"],"function":"require_once"},{"file":"/var/www/html/lib/private/legacy/OC_App.php","line":171,"function":"requireAppFile","class":"OC_App","type":"::","args":[{"__class__":"OCA\\OIDCLogin\\AppInfo\\Application"}]},{"file":"/var/www/html/lib/private/legacy/OC_App.php","line":131,"function":"loadApp","class":"OC_App","type":"::","args":["oidc_login"]},{"file":"/var/www/html/lib/base.php","line":993,"function":"loadApps","class":"OC_App","type":"::","args":[]},{"file":"/var/www/html/index.php","line":37,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/html/lib/autoloader.php","Line":140,"CustomMessage":"App oidc_login threw an error during app.php load and will be disabled: Autoload path not allowed: /var/www/html/apps/files_external/lib/service/globalstoragesservice.php"},"userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.192 Safari/537.36","version":"20.0.7.1"}

**Comment by pulsejet** [comment]
I cannot reproduce this in the official docker image. Did you configure anything else first?

Anyway, I have an inkling what this might be about. See if v1.7.1 fixes this issue.

**Comment by intelligentops** [comment]
@pulsejet thanks for you time.

I also tried with clean setup and it works. Going to find differences in setup.
