### ISSUE TITLE
Will 'oidc_login_proxy_ldap' => false Solve my issue ?

### ISSUE THREAD

**Issue by JonCSgr** [pulsejet/nextcloud-oidc-login#76]
Hello guys i have nextcloud set up syncing with ldap and also have SSO enabled via keycoak
The keycloak server syncs with the very same ldap server nextcloud syncs.

The problem is that upon authenticating users with keycloac nextcloud understands them as two different accounts even though they have the same username/email etc .Everything is identical since they are coming from the same ldap database. 

E.G
This user is the same both in nc & keycloack but its understanded as 2 different accounts who has same name,email just the id added from the keycloak.
![image](https://user-images.githubusercontent.com/61245954/107820421-6c4c1180-6d83-11eb-9023-e5f2c1ef7a94.png)

I would like him to be logged under user101 (ldap one) since i perform API things on him b4hand.
Is 'oidc_login_proxy_ldap' =>  true' made for those kind of situations?

**Comment by pulsejet** [comment]
`oidc_login_proxy_ldap` uses the LDAP user backend. When turned on, Nextcloud will use only the uid provided by OIDC to lookup the user from LDAP and log in if the user exists. Is this what you want to achieve?

**Comment by JonCSgr** [comment]
I think so yes , that is so awesome. I am going to try it now and come back to reply to you 100%.

**Comment by pulsejet** [comment]
The field referred by configured `oidc_login_attributes => id` from OIDC must be whatever you use as the username when logging in with LDAP username-password.
