### ISSUE TITLE
Not logging in

### ISSUE THREAD

**Issue by mmallejac** [pulsejet/nextcloud-oidc-login#78]
Hello,

I am testing the 3 OpenId connectors I've found for Nextcloud, along with my Keycloak server : 
- your OpenID Connect Login 
- Social Login
- [user_oidc](https://github.com/nextcloud/user_oidc)

I was not able to make the latter work. Social Login works fine, but is quite cumbersome to configure. I like the way OpenID Connect Login is designed to uses `config.php` only.

My Keycloak setup is mostly based on [this article](https://janikvonrotz.ch/2020/10/20/openid-connect-with-nextcloud-and-keycloak/). My Nextcloud is 20.0.7 with Docker, using a fresh test instance.

First login tentative brings me directly to the Keycloak login. Unfortunately Sign In brings me back to the Nextcloud login screen : no error logged in the `nextcloud.log`, not error message on page and under the keycloak console I see an active session for my user. Then pressing the OpenID Connect button keeps coming back to the Nextcloud login screen, no more to the keycloak login.

Here what I've added to the config.php` : 

```
  'oidc_login_client_id' => 'nextcloud',
  'oidc_login_client_secret' => 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx',
  'oidc_login_provider_url' => 'https://auth.myurl.comn/auth/realms/test',
  'oidc_login_logout_url' => 'https://auth.myurl.com/auth/realms/test/protocol/openid-connect/logout?redirect_uri=https%3A%2F%2Ftest.cloud.myurl.com%2F',
  'oidc_login_auto_redirect' => true,
  'oidc_login_redir_fallback' => true,
  'oidc_login_attributes' => array(
        'id' => 'preferred_username',
        'mail' => 'email',
  ),
);
```

**Comment by mmallejac** [comment]
Here what I've added to the config.php` : 

```
  'oidc_login_client_id' => 'nextcloud',
  'oidc_login_client_secret' => 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx',
  'oidc_login_provider_url' => 'https://auth.myurl.comn/auth/realms/test',
  'oidc_login_logout_url' => 'https://auth.myurl.com/auth/realms/test/protocol/openid-connect/logout?redirect_uri=https%3A%2F%2Ftest.cloud.myurl.com%2F',
  'oidc_login_auto_redirect' => true,
  'oidc_login_redir_fallback' => true,
  'oidc_login_attributes' => array(
        'id' => 'preferred_username',
        'mail' => 'email',
  ),
);
```

**Comment by pulsejet** [comment]
1. Turn on debug in config.
2. Turn off `oidc_login_redir_fallback`
And try again.

**Comment by mmallejac** [comment]
Disabling `oidc_create_groups` I could see the error message : "Auto creating new users is disabled"
I had missed the `oidc_login_disable_registration` parameter.

Thanks a lot !
