### ISSUE TITLE
Groups management

### ISSUE THREAD

**Issue by mmallejac** [pulsejet/nextcloud-oidc-login#79]
Now I am struggling with Nextcloud groups / Keycloak roles.

I've added 2 roles to the Nextcloud client within Keycloak, and assigned them to my test user : `office` and `admin`. Only `admin` is recognized and added to the user, not the other one. The difference is that `admin`already exist within Nextcloud. Confirmed since if I manually create the `office` group within Nextcloud, the user with this role is then added to that group. 
I can live with that, but looking at your code I see that group creation should work ?!

Also, I am wondering about the specific `admin` group membership : if I try to add my user to the `admin` group using a Keycloak role I can see differences between NC group membership and KC roles assignation. Si I guess that I should use instead the `is_admin` attribute. Without LDAP, how should I declare `is_admin` within Keycloak ?

**Comment by pulsejet** [comment]
Is `oidc_create_groups` set to `true`?

**Comment by mmallejac** [comment]
Yes it is

**Comment by pulsejet** [comment]
Are you on master? The version on the NC app store doesn't have this functionality.

**Comment by mmallejac** [comment]
I see ! I'll test with master, thanks
Also, regarding the `is_admin` attribute : is it preferable to declare a Keycloak user attribute or simply to add `admin` to the group list / roles list ?

**Comment by pulsejet** [comment]
They're equivalent.

**Comment by mmallejac** [comment]
Work great with master, many thanks !
