### ISSUE TITLE
Keycloak - Missing paramter: username

### ISSUE THREAD

**Issue by reavessm** [pulsejet/nextcloud-oidc-login#81]
I hope I'm not doing something stupid, but whenever I login through oidc_login, I get a response from my keycloak server that simply says `{"error":"invalid_request","error_description":"Missing parameter: username"}`.  Here is my relevant config.php

```php
  'oidc_login_client_id' => 'nextcloud-oauth',
  'oidc_login_client_secret' => '<client-secret>',
  'oidc_login_provider_url' => 'https://<keycloak-url>/auth/realms/<realm>',
  'oidc_login_logout_url' => 'https://<keycloak-url>/auth/realms/<realm>/protocol/openid-connect/logout?redirect_uri=https%3A%2F%2F<nextcloud-url>%2F',
  'oidc_login_auto_redirect' => false, # I've tried with both true and false
  'oidc_login_redir_fallback' => false, # I've tried with both true and false
  'oidc_login_scope' => 'openid profile',
  'oidc_login_button_text' => 'SSO',
  'oidc_login_attributes' => array (
    'id' => 'preferred_username',
    'mail' => 'email',
    'quota' => 'nextcloudQuota',
  ),
```

I tried to follow the keycloak example as much as possible, but I can provide the relevant config/logs from there as well if needed

**Comment by pulsejet** [comment]
You get this error from the _Keycloak server_? Are you sure Keycloak is working? If OIDC auth never completes then it's not a problem with this app.

**Comment by reavessm** [comment]
This is the JSON response that I'm getting from the keycloak server. It seems like NextCloud is not sending all the information needed to keycloak to begin with

**Comment by reavessm** [comment]
To be honest with you, I don't know how to check that.  I just followed the instructions from this wiki.  How do I check if my Keycloak client is configured for the authcode grant?  I don't see an authcode nor grant type option in the client settings.

**Comment by pulsejet** [comment]
I have never used Keycloak, so I have no idea either. Maybe someone else can help.

But if Keycloak expects a "username", I expect something is wrong with it's configuration. Maybe double check if you created your client correctly from instructions [here](https://www.keycloak.org/docs/latest/server_admin/#_clients)

**Comment by stevesobol** [comment]
I'm a Keycloak user (and developer, actually, as of a few months ago - I now have some experience creating themes and system extensions; specifically, a User Storage provider that I needed to create for my rather unique use-case). Being waist-deep in Keycloak for the past three or four months has been educational ;) 

I'm wiring up several services I'm setting up to use Keycloak for SSO. Nextcloud's actually the first of many. 

So, let's chat!

**Comment by stevesobol** [comment]
Tonight, I am working on setting up OIDC using this plugin. So far, I've configured Keycloak, configured Nextcloud, and I can hit my Nextcloud URL and get redirected to my Keycloak login page, enter valid credentials for a test user, and get kicked back to Nextcloud, which complains because I haven't created my test user in Nextcloud yet. In other words, everything's working properly. (I have disabled auto-registration, so the behavior I'm seeing is the behavior I want to see.)

@pulsejet yes, that chunk of JSON shared by @reavessm is definitely coming from Keycloak. I think we need to take a look at the relevant Keycloak configs. @reavessm please post your client configuration, with any passwords or sensitive information redacted.

**Comment by reavessm** [comment]
@stevesobol  I exported my client from keycloak and this is what I got:

```json
{
    "clientId": "nextcloud",
    "surrogateAuthRequired": false,
    "enabled": true,
    "alwaysDisplayInConsole": false,
    "clientAuthenticatorType": "client-secret",
    "redirectUris": [
        "https://nextcloud.<domain.com>/*"
    ],
    "webOrigins": [],
    "notBefore": 0,
    "bearerOnly": false,
    "consentRequired": false,
    "standardFlowEnabled": true,
    "implicitFlowEnabled": false,
    "directAccessGrantsEnabled": true,
    "serviceAccountsEnabled": false,
    "publicClient": false,
    "frontchannelLogout": false,
    "protocol": "openid-connect",
    "attributes": {
        "saml.assertion.signature": "false",
        "saml.multivalued.roles": "false",
        "saml.force.post.binding": "false",
        "saml.encrypt": "false",
        "saml.server.signature": "false",
        "backchannel.logout.revoke.offline.tokens": "false",
        "saml.server.signature.keyinfo.ext": "false",
        "exclude.session.state.from.auth.response": "false",
        "id.token.signed.response.alg": "",
        "backchannel.logout.session.required": "false",
        "client_credentials.use_refresh_token": "false",
        "saml_force_name_id_format": "false",
        "saml.client.signature": "false",
        "tls.client.certificate.bound.access.tokens": "false",
        "saml.authnstatement": "false",
        "display.on.consent.screen": "false",
        "saml.onetimeuse.condition": "false"
    },
    "authenticationFlowBindingOverrides": {},
    "fullScopeAllowed": true,
    "nodeReRegistrationTimeout": -1,
    "defaultClientScopes": [
        "web-origins",
        "role_list",
        "roles",
        "profile",
        "email"
    ],
    "optionalClientScopes": [
        "address",
        "phone",
        "offline_access",
        "microprofile-jwt"
    ],
    "access": {
        "view": true,
        "configure": true,
        "manage": true
    }
}
```

Please let me know if you need any more info, thanks

**Comment by stevesobol** [comment]
Holy crap, that's a lot.

You probably shouldn't have any `saml-*` attributes set. You're not using SAML; you're using OpenID Connect.

I just exported my client... here's the JSON. I changed almost nothing from the defaults. I'm running the latest Keycloak - v12.0.4.

```
{
  "realm": "<MY REALM NAME>",
  "auth-server-url": "https://<MY KEYCLOAK SERVER'S HOSTNAME>/auth",
  "ssl-required": "external",
  "resource": "nextcloud",
  "public-client": true,
  "confidential-port": 0
}
```

I'm actually not sure where `resource` gets set.

Try creating a new client, and setting the following things - I'm assuming you're using a recent version of Keycloak...

On the Settings tab:
* Client ID
* Client Protocol - OpenID Connect
* Valid Redirect URIs

I also added a custom mapper for `ownCloudQuota`:
* Mapper Type: **User Attribute**
* User Attribute: **ownCloudQuota**
* Token Claim Name: **ownCloudQuota**
* Claim JSON Type: **String**
* Add to ID Token, Add to Access Token, Add to userinfo: **On**. Multivalued, Aggregate attribute values: **Off**.

And, a custom mapper for `ownCloudGroups`:
* Mapper Type: **User Client Role**
* Client Role prefix: **(Leave blank)**
* Multivalued: **On**
* Token Claim Name: **ownCloudGroups**
* Claim JSON Type: **String**
* Add to ID Token, Add to Access Token, Add to userinfo: **On**.

**Comment by stevesobol** [comment]
How did those SAML attributes make it into your configs? I'm wondering if that may be the problem.

**Comment by reavessm** [comment]
I deleted the nextcloud client from keycloak, recreated it, only adding the valid redirect uri and changing Access Type from public to confidential so I can get a client id/secret, now I"m getting the error:

```
[0m[31m13:16:35,380 ERROR [org.keycloak.headers.DefaultSecurityHeadersProvider] (default task-2) MediaType not set on path /auth/realms/<realm>/protocol/openid-connect/auth, with response status 500
[0m[31m13:16:35,381 ERROR [io.undertow.request] (default task-2) UT005023: Exception handling request to /auth/realms/<realm>/protocol/openid-connect/auth: java.lang.RuntimeException: java.lang.RuntimeException: org.jboss.resteasy.spi.UnhandledException: javax.ws.rs.InternalServerErrorException: HTTP 500 Internal Server Error
```

I also tried exporting the nextcloud client, deleting the `saml-*` attributes and reimporting that as a new client, and importing the json of your client, but neither worked.  I am also running keycloak 12.0.4.  I'm running both nextcloud and keycloak on openshift

**Comment by reavessm** [comment]
After recreating a new keycloak instance, new realm, new client, and changing the info accordingly, I am able to login to keycloak through nextcloud, but I am getting a different error on the Nextcloud side.  Thanks to @stevesobol for the help, but I am going to close this issue since this issue was largely created by something on the keycloak side.
