### ISSUE TITLE
LDAP Proxy Mode: Update/Sync attributes

### ISSUE THREAD

**Issue by DonCarlosGraz** [pulsejet/nextcloud-oidc-login#84]
Thank you for the plugin!

We use the setting "oidc_login_proxy_ldap" => true.
Now the ldap attributes like email are not set (as intended, see https://github.com/pulsejet/nextcloud-oidc-login/blob/master/lib/Controller/LoginController.php#L277), but we wonder how this attributes should be synced. Are we missing any configuration (e.g. in the LDAP plugin)?

**Comment by pulsejet** [comment]
Probably. This plugin has nothing to do with LDAP sync.

**Comment by DonCarlosGraz** [comment]
thank you for the info, we will further investigate it.

**Comment by DonCarlosGraz** [comment]
Hm, we found out, that in our NC-Version (19.0.9.1) the method `$ldapUser->update();` (https://github.com/pulsejet/nextcloud-oidc-login/blob/master/lib/Controller/LoginController.php#L180) does not exist;
When we replace the statement (L179-181) e.g. with the statement `$ldapUser->updateEmail();` then the email attribute was updated.

**Comment by DonCarlosGraz** [comment]
We upgrade to NC 20.x, but the problem still exists.
Is this a "normal" behaviour?
Can we do anything to solve this issue?

**Comment by DonCarlosGraz** [comment]
Does anyone have a similar problem?

**Comment by skainz** [comment]
Hello, thanks for the fix/patch, we had the same issue on one of our systems.  I applied the fix from @DonCarlosGraz and ist works. Please integrate this in the plugin if possible, so we don't have to fix it manually for every new install.
 Thank you!

**Comment by DonCarlosGraz** [comment]
thanks!
