### ISSUE TITLE
Backdoor for local login

### ISSUE THREAD

**Issue by stevesobol** [pulsejet/nextcloud-oidc-login#87]
Hello! I'm new to Nextcloud and your OIDC plugin, and I have one question:

With auto-redirect enabled, I have no way to log in as my local admin user. 

99.9% of the time, I won't need or want to log in as a local user, nor will I want anyone else to be able to do so.

I will have at least one account I can log into using SSO that has admin privileges, and I generally won't ever need to log in locally - but in the unlikely event that I DO want to log in as my local admin user, is there a way to bypass the automatic redirection without logging onto my web server and changing settings in config.php?

Thanks :)

**Comment by pulsejet** [comment]
Use `noredir`, e.g. `http://your-domain.com/nextcloud/index.php/login?noredir=1`
