### ISSUE TITLE
Keycloak and existing users

### ISSUE THREAD

**Issue by KodoGit** [pulsejet/nextcloud-oidc-login#88]
Hi.
I have Nextcloud with users synced from AD and want to setup OpenID for it using Keycloak.
But this app aswell as Social Login always return errors like "Auto creating new users is disabled".
I don't want to create new users but to allow login with Keycloak.
Looks like it uses wrong name for mapping Keycloak and Nextcloud users.
Any working setting exists? All guides that I've found mentions creating new users with Keycloak...

**Comment by KodoGit** [comment]
The problem is that NC uses AD guids as usernames and in uppercase. 
I can set up attribute mapper in KC and use it as id:
  'oidc_login_attributes' => array(    
    'id' => 'LDAP_ID',
But this will end with guid as username in lowercase...

**Comment by KodoGit** [comment]
I had to do this in LoginController.php
```
        // Get UID
        $uid = strtoupper($profile[$attr['id']]);
```

**Comment by Blackclaws** [comment]
I think you should be able to configure which attribute is used as id in the ldap backend settings, not sure however.

**Comment by KodoGit** [comment]
> 
Keycloak script mapper is disabled and not recomended to use. So I can't change something on Keycloak side. And it was too difficult for me anyway. 
I've updated Nextcloud and this app. The problem is still here.
No app for open-id works because Keycloack turns everything to lowercase.
And I cant get what to change in the new code as I have very basic php understanding.
I need some help to change the case of the login.
