### ISSUE TITLE
Unable to verify JWT claims

### ISSUE THREAD

**Issue by nils-one** [pulsejet/nextcloud-oidc-login#92]
Hi there,
I stuck in the authorization process with the error message "Unable to verify JWT claims" but I can't figure what went wrong here. Is there any way to get more information about this error?

**Comment by pulsejet** [comment]
Does your OIDC provider work with other clients? Probably something is wrong with your provider

**Comment by nils-one** [comment]
Oh sorry, forgot to write here. It was the fault of the provider. There was a redirect that cuts the last digits of the URL. Thank for your help!
