### ISSUE TITLE
bug: app passwords change on log-in

### ISSUE THREAD

**Issue by xcojonny** [pulsejet/nextcloud-oidc-login#94]
Hello,

First of all thanks for your work!

I’ve encountered a problem. Don’t know whether it’s a bug or not. 

system:
- nexcloud 21 on Docker behind traefik 
- Keycloak as SSO connected to nextcloud via oicd-login.
- Everything works so far. 

Issue:
- login to Nextcloud Account via opened connect with the help of keycloak, local login disabled. 
- register iOS apps
- generating and using app passwords
- everything functions
- approx 15 min later the app passwords are invalid and the iOS apps for Nextcloud need to reregister. 
- disable OpenID connect
- login with local credentials
- app passwords work again and the iOS App are not asking for reauthentification  

Any ideas? Every help is welcome.

**Comment by pulsejet** [comment]
This is strange; the app doesn't interfere here at all. Any insights appreciated.

**Comment by xcojonny** [comment]
Anything that I can do to provide more info? 

Or maybe it's a typical man in front the screen problem 🦆?

**Comment by LotusAxt** [comment]
Same problem here. Logging in via OIDC invalidates all App Passwords. 
Further more, it looks for me like I can have only one active Session when I use OIDC.
Example:
- Login on Desktop with OIDC and connect the Desktop App (Works fine)
- Login with OIDC on my mobile (Android) works fine
- Some time later go back to the Desktop -> it's logged out
- Login again on Desktop
- After some time go back to mobile -> it's logged out

If I don't try to re login on my mobile, the Desktop Session seems to keep valid (at least over night).
After each login procedure the App Passwords I've generated with the (now logged out session) becoming invalid.

I've just migrated from native Nextcloud login to OIDC. So my OIDC login is mapping to an existing account. (Maybe that's Part of the Problem) 

Nextcloud 21
Keycloak as SSO provider

**Comment by xcojonny** [comment]
Logging in on my iPhone (Browser) being logged in on my tablet (browser) does not log out my iPad session neither my iPhone session is.

@LotusAxt do you have the same behavior with other apps? Maybe your 2nd issue is keycloak related?

**Comment by DanWiseProgramming** [comment]
@pulsejet Just wanted to add that this is also being discussed over in the Nextcloud Server repository: https://github.com/nextcloud/server/issues/26502

I use this plugin with Nextcloud & Keycloak and upgrading from 21.0.0.18 to 21.0.1.1 introduced this issue for me.
I have not yet tried with v1.8.0 of this plugin yet (currently on 1.7.1) due to #95 .

**Comment by DanWiseProgramming** [comment]
This change in Nextcloud was made which may mean that this plugin needs to be updated to account for this change: https://github.com/nextcloud/server/pull/25571/commits/0ea266e8bffefef2091b8ad42f08d189107fe7b9

https://github.com/nextcloud/server/pull/25571

**Comment by fpellet** [comment]
I have same problem on 21.0.1

If I remove line `$this->session->set('last-password-confirm', time());` in LoginController, I have not this bug

**Comment by pulsejet** [comment]
Can you try with latest `master` (NC20+) or the `nc19` branch for lower?

In particular you want to try [this patch](https://github.com/pulsejet/nextcloud-oidc-login/commit/3a50a43611d859daed44b065db86b16225052404)

**Comment by fpellet** [comment]
I try with 21.0.1 and 2.0.1. It seems to work.
Thank you

**Comment by pulsejet** [comment]
@fpellet more details? Any error/logs in debug mode?

**Comment by fpellet** [comment]
No error for this issue. I have just `Login failed: 'fpellet' (Remote IP: '******')` and nextcloud apps is disconnected.

Scenario:
- In browser, I connect to nextcloud web.
- In nextcloud app, I connect with browser and synchronize
- In other browser, I connect to nextcloud web with same account
- wait
- The nextcloud app is disconnected

**Comment by xcojonny** [comment]
Thanks!!
I've updated 2 hours ago. Until now everything is working pretty fine.

No errors in my nextcloud log. 

I'll post if there's anything coming up related to this...


Nextcloud 21.0.1
OIC 2.0.1

**Comment by LotusAxt** [comment]
I installed the update this morning and until now everything seems to work. :)
Thank you!

Nextcloud 21.0.1
OIC 2.0.1

**Comment by digitalcraig** [comment]
Nextcloud: 21.0.1
OIC: 2.0.1

Using OIC with Keycloak, I just updated OIC this morning and updated Nextcloud to 21.0.1 last week. My app passwords stopped after updating OIC this morning. I attempted to delete the old app password and create a new one, but it prompts me to put in my existing Nextcloud password.

**Comment by pulsejet** [comment]
@digitalcraig try v2.0.2? Need more details if that doesn't work.

**Comment by digitalcraig** [comment]
@pulsejet v2.0.2 seems to have resolved my issue. Thanks!

**Comment by fpellet** [comment]
Same for me. It's works with v2.0.2 on 21.0.1. Thanks
